/**
 * THE PITFALL REGISTRY — 1000 documented player complaints about rugby games,
 * and what this engine does about each one.
 *
 * Sourced from player reviews and forum threads covering rugby titles from 1995
 * to 2026. Each entry is a real class of complaint, its root cause expressed as
 * an engineering fault, the fix shipped here, and the setting or system that
 * implements it. Status is honest: some things are fixed, some are designed
 * around, and a few are recorded as accepted limitations.
 */

export type FixStatus = 'FIXED' | 'DESIGNED_AROUND' | 'ACCEPTED';

export interface Pitfall {
  id: string;
  cat: string;
  complaint: string;
  cause: string;
  fix: string;
  inGame: string;
  status: FixStatus;
}

export const CATEGORIES = [
  'PASSING', 'AI SHAPE', 'RUCKS', 'SCRUMS', 'LINEOUTS', 'KICKING',
  'TACKLING', 'LAWS & REFEREE', 'FLOW & PACING', 'CAMERA & FEEDBACK',
  'CONTROLS', 'PROGRESSION', 'AUDIO & ATMOSPHERE', 'STABILITY',
] as const;

export const PITFALLS: Pitfall[] = [
  /* ---------------- PASSING ---------------- */
  { id: 'P-001', cat: 'PASSING', complaint: 'Passes do not go to hand. They bounce on the grass.', cause: 'Ball is thrown to a world coordinate computed at press time, with no solver for receiver motion during flight.', fix: 'Every pass targets a live receiver. Flight time is solved so ball and receiver arrive at the same point simultaneously.', inGame: 'Pass solver + guaranteed catch unless a stated error roll fails.', status: 'FIXED' },
  { id: 'P-002', cat: 'PASSING', complaint: 'Passes are thrown into no-man\'s-land for no reason I can fathom.', cause: 'No receiver validity check — the pass goes to the ghost of a slot rather than to a man.', fix: 'If no eligible receiver exists on that side, the button does nothing and the prompt says why.', inGame: 'Pass option ranking; blocked inputs shown in the command bar.', status: 'FIXED' },
  { id: 'P-003', cat: 'PASSING', complaint: 'A long pass launches into the grandstand.', cause: 'Pass distance derived from button pressure rather than from the shape.', fix: 'Distance clamped to the widest eligible receiver. A cut-out pass can never exceed the shape width.', inGame: 'Cut-out pass with hard distance clamp.', status: 'FIXED' },
  { id: 'P-004', cat: 'PASSING', complaint: 'Computer-controlled teammates do not run good running lines.', cause: 'Receivers hold a static offset instead of running a line onto the ball.', fix: 'Receivers run curved lines timed to the pass, always forward of the passer and onto the ball.', inGame: 'Running-line engine with depth and curve per role contract.', status: 'FIXED' },
  { id: 'P-005', cat: 'PASSING', complaint: 'It is very hard to run a smooth backline play.', cause: 'Pass cadence gated by animation length rather than by ball availability.', fix: 'The nine passes the moment the ball is available. Distribution is not queued behind a wind-up.', inGame: 'Zero-frame distribution at the ruck.', status: 'FIXED' },
  { id: 'P-006', cat: 'PASSING', complaint: 'Passing from a ruck, my player stands still and the defence is on me.', cause: 'Receiver velocity starts at zero; defenders are already at full pace.', fix: 'The receiver is already moving when the ball arrives, at 80 percent of top speed, onto the line.', inGame: 'Momentum carry-out on every pass.', status: 'FIXED' },
  { id: 'P-007', cat: 'PASSING', complaint: 'The pass button just does not work sometimes.', cause: 'Input buffered behind a locked animation state and dropped on transition.', fix: 'Inputs are sampled every frame and never queued. A press during a transition resolves on the first available frame and is never discarded.', inGame: 'Frame-sampled input with a one-frame grace buffer.', status: 'FIXED' },
  { id: 'P-008', cat: 'PASSING', complaint: 'Passes get pinged sixty metres downfield.', cause: 'No upper bound on pass velocity.', fix: 'Ball speed capped at 18 m/s; a spiral is the only pass that may exceed 15 m/s and only to a visible target.', inGame: 'Pass velocity model.', status: 'FIXED' },
  { id: 'P-009', cat: 'PASSING', complaint: 'You cannot choose which side to pass to with any confidence.', cause: 'Pass direction inferred from stick angle rather than from named receivers.', fix: 'Pass left and pass right are separate verbs. Cut-out variants skip exactly one receiver.', inGame: 'Four pass verbs: short L/R and cut-out L/R.', status: 'FIXED' },
  { id: 'P-010', cat: 'PASSING', complaint: 'Interceptions happen from an offside position.', cause: 'Intercept check is a sphere around the defender with no legality test.', fix: 'An interception requires the defender to be onside and to have been tracking the ball for 0.4 s.', inGame: 'Offside-gated intercept with a tracking requirement.', status: 'FIXED' },
  { id: 'P-011', cat: 'PASSING', complaint: 'The dummy pass does nothing.', cause: 'No defender response model — the fake changes nothing in the defence.', fix: 'A dummy bites the inside defender for 0.35 s, opening the outside channel measurably.', inGame: 'Dummy verb with a defender reaction model.', status: 'FIXED' },
  { id: 'P-012', cat: 'PASSING', complaint: 'Offloads never come off.', cause: 'Offload probability is a flat low constant independent of the situation.', fix: 'Offload chance scales with carrier skill, tackle quality and the presence of a support runner at the hip.', inGame: 'Support-aware offload model.', status: 'FIXED' },
  { id: 'P-013', cat: 'PASSING', complaint: 'The offload goes to nobody.', cause: 'No check for a support runner before the offload is permitted.', fix: 'The offload is only available when a support runner is inside 3 m. Otherwise the carrier takes the tackle and presents.', inGame: 'Support proximity gate.', status: 'FIXED' },
  { id: 'P-014', cat: 'PASSING', complaint: 'You cannot pass while being tackled.', cause: 'Tackle state terminates the pass verb entirely.', fix: 'An offload window of 0.25 s opens at the moment of contact and is always to a named support.', inGame: 'Contact-window offload.', status: 'FIXED' },
  { id: 'P-015', cat: 'PASSING', complaint: 'Passing feels clunky, like a mobile game.', cause: 'Pass resolves after a wind-up animation.', fix: 'Pass resolves on the frame of the press. The animation is decorative, not gating.', inGame: 'Immediate pass resolution.', status: 'FIXED' },
  { id: 'P-016', cat: 'PASSING', complaint: 'Receivers run backwards to collect the ball.', cause: 'Target solved behind the receiver.', fix: 'All pass targets are forward of the passer by a minimum of 0.4 m per metre of pass distance.', inGame: 'Pass target forwardness rule.', status: 'FIXED' },
  { id: 'P-017', cat: 'PASSING', complaint: 'You cannot see who you are passing to.', cause: 'No receiver indication.', fix: 'The intended receiver is highlighted with a marker and his name before the press commits.', inGame: 'Pass-target indicator in the HUD and in-world.', status: 'FIXED' },
  { id: 'P-018', cat: 'PASSING', complaint: 'The ball sails over the backline.', cause: 'Flat pass solved with too much vertical velocity.', fix: 'Flight is a solved arc with a fixed arrival height at chest level.', inGame: 'Pass arc solver.', status: 'FIXED' },
  { id: 'P-019', cat: 'PASSING', complaint: 'Passes get batted down by nobody in particular.', cause: 'Random deflection roll not tied to any defender.', fix: 'A deflection requires a defender inside 1.2 m of the line of flight. Nothing happens without a body.', inGame: 'Line-of-flight deflection test.', status: 'FIXED' },
  { id: 'P-020', cat: 'PASSING', complaint: 'You cannot run a loop or an angle.', cause: 'Only straight lateral offsets are available.', fix: 'Set plays include loops, switches, misses and crosses, each with named runner instructions.', inGame: 'Ten set plays callable at any ruck, scrum or lineout.', status: 'FIXED' },
  { id: 'P-021', cat: 'PASSING', complaint: 'Passing out of your own twenty-two is suicide.', cause: 'Defenders arrive before the ball does.', fix: 'The nine distributes at full speed and the first receiver starts moving on release, so the ball beats the rush.', inGame: 'Distribution speed plus momentum carry-out.', status: 'FIXED' },
  { id: 'P-022', cat: 'PASSING', complaint: 'Scrum halves take an age to move the ball.', cause: 'A fixed post-ruck delay before distribution.', fix: 'Distribution delay is a function of ruck quality only: 0.5 s for quick ball, 1.6 s for slow. Never longer.', inGame: 'Ruck-speed-driven distribution, hard capped.', status: 'FIXED' },
  { id: 'P-023', cat: 'PASSING', complaint: 'The pass goes the opposite direction to the input.', cause: 'Direction resolved relative to camera rather than to the attacking line.', fix: 'Pass direction is resolved relative to the attacking direction and the carrier\'s shoulders, never to the camera.', inGame: 'Attack-relative pass mapping.', status: 'FIXED' },
  { id: 'P-024', cat: 'PASSING', complaint: 'Pass accuracy does not seem to relate to the player.', cause: 'Accuracy is a global constant.', fix: 'Accuracy is per player, driven by the HANDLING attribute, the wet-ball state and the pressure on the passer.', inGame: 'Per-player handling model.', status: 'FIXED' },
  { id: 'P-025', cat: 'PASSING', complaint: 'You cannot pass with any finesse — it is all or nothing.', cause: 'One pass type.', fix: 'Six pass behaviours: short, cut-out, spiral, dummy, pop and offload.', inGame: 'Pass behaviour table.', status: 'FIXED' },

  /* ---------------- AI SHAPE ---------------- */
  { id: 'A-001', cat: 'AI SHAPE', complaint: 'Players are never in their correct position.', cause: 'Positions are emergent from a generic steering behaviour with no positional authority.', fix: 'Fifteen role contracts, one per shirt, each specifying lateral offset and depth for every phase.', inGame: 'Role contract table, 15 shirts × 7 phases.', status: 'FIXED' },
  { id: 'A-002', cat: 'AI SHAPE', complaint: 'Props line up at fly-half while full-backs are rucking.', cause: 'Role assignment by proximity rather than by shirt number.', fix: 'Role assignment is by shirt number. A prop can never occupy a back\'s slot.', inGame: 'Contract-for-shirt lookup, hard wired.', status: 'FIXED' },
  { id: 'A-003', cat: 'AI SHAPE', complaint: 'Pointless having a backline because the forwards play fly-half.', cause: 'First receiver is whoever is nearest.', fix: 'The ten is first receiver on every phase unless a forward carry is explicitly called.', inGame: 'First-receiver contract on shirt 10.', status: 'FIXED' },
  { id: 'A-004', cat: 'AI SHAPE', complaint: 'No player repositioning — nobody returns to their normal position.', cause: 'No reset behaviour between phases.', fix: 'Shape re-forms within two seconds of the ball being cleared, from the contract, every phase.', inGame: 'Shape reset on ball availability.', status: 'FIXED' },
  { id: 'A-005', cat: 'AI SHAPE', complaint: 'Your right prop ends up on the wing facing a winger.', cause: 'Forwards follow the ball laterally without limit.', fix: 'Forwards are clamped to the channels their contract allows. A prop never exceeds the ten channel.', inGame: 'Lateral clamp per shirt.', status: 'FIXED' },
  { id: 'A-006', cat: 'AI SHAPE', complaint: 'Three players float around the ruck instead of coming into it.', cause: 'No arrival order and no commitment signal.', fix: 'Three players are assigned to every breakdown by name, in arrival order, before the tackle is even made.', inGame: 'Pre-assigned breakdown crew.', status: 'FIXED' },
  { id: 'A-007', cat: 'AI SHAPE', complaint: 'Support runners do not arrive.', cause: 'Support is a single vague follow behaviour.', fix: 'The openside flanker rides the carrier\'s hip and the eight trails at four metres on every carry.', inGame: 'Support contracts on shirts 7 and 8.', status: 'FIXED' },
  { id: 'A-008', cat: 'AI SHAPE', complaint: 'Teammates simply run back into busy areas.', cause: 'Target is the ball, not space.', fix: 'Attackers target the gap between defenders, never the ball carrier\'s position.', inGame: 'Gap-seeking target selection.', status: 'FIXED' },
  { id: 'A-009', cat: 'AI SHAPE', complaint: 'Huge gaps left in the defensive line cause easy line breaks.', cause: 'Defenders space themselves by fixed count, not by pitch width.', fix: 'The line distributes across the width actually available with a hard maximum spacing of four metres.', inGame: 'Connected-line solver.', status: 'FIXED' },
  { id: 'A-010', cat: 'AI SHAPE', complaint: 'The AI is useless on defence — it parts like the Red Sea.', cause: 'Defenders react to the carrier only after a long reaction delay.', fix: 'Defenders react inside 0.15 s and hold their lane. The line never opens a hole wider than four metres by accident.', inGame: 'Reaction cap plus lane discipline.', status: 'FIXED' },
  { id: 'A-011', cat: 'AI SHAPE', complaint: 'The CPU does one pass and goes into a tackle. Repeat. No intelligence at all.', cause: 'CPU attack has no plan, only a per-carrier decision.', fix: 'The CPU enters each phase with a called play and a target channel, and commits to it across three phases.', inGame: 'CPU play-calling with phase continuity.', status: 'FIXED' },
  { id: 'A-012', cat: 'AI SHAPE', complaint: 'I put my controller down and the CPU did nothing but that.', cause: 'CPU attack has no fallback when the primary play is closed.', fix: 'If the called play is closed, the CPU escalates: pod carry, then wide sweep, then kick. It never repeats a failed play.', inGame: 'Play escalation ladder.', status: 'FIXED' },
  { id: 'A-013', cat: 'AI SHAPE', complaint: 'The CPU runs out into touch with the ball.', cause: 'No touchline awareness in the steering target.', fix: 'A steering target is never placed within 2.5 m of touch, and the CPU carrier steps infield inside 5 m of touch.', inGame: 'Touchline avoidance.', status: 'FIXED' },
  { id: 'A-014', cat: 'AI SHAPE', complaint: 'Players react with a big delay in defence.', cause: 'A single global reaction timer.', fix: 'Reaction is per player, driven by AWARENESS, capped at 0.2 s, and is never scaled up to create difficulty.', inGame: 'Per-player awareness reaction.', status: 'FIXED' },
  { id: 'A-015', cat: 'AI SHAPE', complaint: 'The full-back joins the line and leaves nobody at home.', cause: 'No sweeper contract.', fix: 'The fifteen sweeps on every phase and only ever joins the line when the overlap count is two or more.', inGame: 'Sweeper contract on shirt 15.', status: 'FIXED' },
  { id: 'A-016', cat: 'AI SHAPE', complaint: 'Wings come in and ruck.', cause: 'No prohibition on backs entering breakdowns.', fix: 'Shirts 11, 13, 14 and 15 are contractually forbidden from entering a ruck.', inGame: 'Ruck ineligibility list.', status: 'FIXED' },
  { id: 'A-017', cat: 'AI SHAPE', complaint: 'The scrum half gets trapped in the ruck and a forward has to fetch the ball from thirty metres away.', cause: 'Receiver selection by nearest-anyone with no eligibility order.', fix: 'Eligibility order for playing the ball at a ruck: nine, then eight, then two. Never a back from distance.', inGame: 'Ruck distribution eligibility order.', status: 'FIXED' },
  { id: 'A-018', cat: 'AI SHAPE', complaint: 'Forwards stand in the backline doing nothing.', cause: 'Forwards have no job between carries.', fix: 'Between carries forwards hold a pod behind the ruck, ready to take the next ball, and are the first to the following breakdown.', inGame: 'Pod contract for shirts 1 to 8.', status: 'FIXED' },
  { id: 'A-019', cat: 'AI SHAPE', complaint: 'Defensive line speed is inconsistent, sometimes rush, sometimes passive.', cause: 'Line speed derived from difficulty level rather than from the system and the situation.', fix: 'Line speed is a property of the defensive system and the slider, and is constant within a match.', inGame: 'System-driven line speed.', status: 'FIXED' },
  { id: 'A-020', cat: 'AI SHAPE', complaint: 'Defenders shoot up out of the line and leave the outside uncovered.', cause: 'Individual defenders choose to rush without a system-level agreement.', fix: 'Rush, drift and umbrella are system-wide. Either the whole line rushes or none of it does.', inGame: 'System-level defensive assignments.', status: 'FIXED' },
  { id: 'A-021', cat: 'AI SHAPE', complaint: 'Nobody chases kicks.', cause: 'Chase assignment is implicit.', fix: 'Three chasers with named lanes are assigned the moment the kick is struck.', inGame: 'Kick-chase lane assignment.', status: 'FIXED' },
  { id: 'A-022', cat: 'AI SHAPE', complaint: 'Nobody fields the high ball.', cause: 'No receiver call.', fix: 'The fifteen calls for the ball and has priority. Wings contest only when he is out of position.', inGame: 'Kick-receive priority order.', status: 'FIXED' },
  { id: 'A-023', cat: 'AI SHAPE', complaint: 'The AI kicks aimlessly.', cause: 'Kick decision is a random roll.', fix: 'CPU kicks are chosen from a table of eight kick types, selected by field position, chase quality and wind.', inGame: 'Situational kick selection.', status: 'FIXED' },
  { id: 'A-024', cat: 'AI SHAPE', complaint: 'The AI does not manage the clock at the end of a match.', cause: 'No clock state in the decision model.', fix: 'A leading CPU kicks to touch and slows the ball after the seventieth minute. A trailing CPU raises tempo and risks.', inGame: 'Clock-aware decision weighting.', status: 'FIXED' },
  { id: 'A-025', cat: 'AI SHAPE', complaint: 'The AI never takes a drop goal when it should.', cause: 'Drop goal is not in the option table for the CPU.', fix: 'Drop goal is a weighted CPU option inside the 40 m zone with the clock against them.', inGame: 'CPU drop-goal option.', status: 'FIXED' },
  { id: 'A-026', cat: 'AI SHAPE', complaint: 'Winning scrums and lineouts is far too easy.', cause: 'Set-piece outcome weighted to the human.', fix: 'Set-piece outcome is a pure rating contest with a small skill input, and the input is legible.', inGame: 'Rating-led set-piece model.', status: 'FIXED' },
  { id: 'A-027', cat: 'AI SHAPE', complaint: 'Sidestepping destroys every tackle attempt.', cause: 'Evade chance is high and independent of the defender\'s positioning.', fix: 'A step only beats a defender who is square-on and inside 2.5 m. A lateral defender cannot be stepped.', inGame: 'Step validity test.', status: 'FIXED' },
  { id: 'A-028', cat: 'AI SHAPE', complaint: 'The computer gives away penalties too easily.', cause: 'Penalty roll is constant and high.', fix: 'Discipline is an attribute. A disciplined side concedes half the penalties of an undisciplined one, and never in bulk.', inGame: 'Discipline attribute in the penalty model.', status: 'FIXED' },
  { id: 'A-029', cat: 'AI SHAPE', complaint: 'There is no difference between teams — everyone plays the same.', cause: 'One shared AI profile.', fix: 'Five CPU archetypes with different kick, width, offload and set-piece biases, plus per-team ratings.', inGame: 'Archetype and ratings model.', status: 'FIXED' },
  { id: 'A-030', cat: 'AI SHAPE', complaint: 'Higher difficulty just makes the AI cheat.', cause: 'Difficulty applied as a stat multiplier.', fix: 'Difficulty scales decision quality only — reaction, error and read rates. Never speed, never strength.', inGame: 'Ten rungs scaling decisions, not physics.', status: 'FIXED' },
  { id: 'A-031', cat: 'AI SHAPE', complaint: 'Players bump into each other and get stuck.', cause: 'No local separation behaviour.', fix: 'Teammates apply separation and never block their own carrier. Friendly collision is disabled inside 2 m of the ball.', inGame: 'Separation and no-friendly-block.', status: 'FIXED' },
  { id: 'A-032', cat: 'AI SHAPE', complaint: 'You get blocked by your own players at the base of the ruck.', cause: 'Ruck participants stand up in the carrier\'s path.', fix: 'Clearers finish past the ball and exit laterally, never standing up in the gate.', inGame: 'Clearer exit path.', status: 'FIXED' },
  { id: 'A-033', cat: 'AI SHAPE', complaint: 'Substitutions are made by the AI at random times.', cause: 'No fatigue logic.', fix: 'Bench use is driven by live per-player fatigue and always replaces the most tired forward first.', inGame: 'Fatigue-driven bench logic.', status: 'FIXED' },

  /* ---------------- RUCKS ---------------- */
  { id: 'R-001', cat: 'RUCKS', complaint: 'Rucks are a total button-mash mess.', cause: 'Resolution is a raw alternating-press counter with no legible state.', fix: 'The ruck shows a live force bar, the number committed on each side, and who is winning. The mash is optional and off by default.', inGame: 'Legible ruck contest; manual waggle is an option.', status: 'FIXED' },
  { id: 'R-002', cat: 'RUCKS', complaint: 'It is extremely hard to steal the ball, so defence is just mashing.', cause: 'Jackal chance is a low constant regardless of numbers.', fix: 'Jackal chance scales with the difference in committed players, the arriving player\'s AWARENESS, and ball speed.', inGame: 'Numbers-and-quality jackal model.', status: 'FIXED' },
  { id: 'R-003', cat: 'RUCKS', complaint: 'When I do win a contest I cannot tell why.', cause: 'No feedback on resolution.', fix: 'Every ruck resolution prints one line stating the margin and the reason.', inGame: 'Ruck resolution caption.', status: 'FIXED' },
  { id: 'R-004', cat: 'RUCKS', complaint: 'Turnovers are constant and unavoidable.', cause: 'Independent turnover rolls with no player agency.', fix: 'Turnover only occurs when the defence legally wins it: numbers advantage or a clean jackal. Never at random.', inGame: 'Legal-turnover-only rule.', status: 'FIXED' },
  { id: 'R-005', cat: 'RUCKS', complaint: 'A random player picks and grubbers the ball when I did not ask for that.', cause: 'Action queue combined with a context misread.', fix: 'No action is queued. Playing the ball at the ruck is an explicit choice between pick-and-go and pass.', inGame: 'Explicit ball-play choice; nothing queued.', status: 'FIXED' },
  { id: 'R-006', cat: 'RUCKS', complaint: 'The game waits for an arbitrary player to walk to the back of the ruck.', cause: 'Receiver selection by nearest-anyone with no fast path.', fix: 'Distribution is instant from whoever is eligible and present, in the order nine, eight, two.', inGame: 'Eligibility order with instant distribution.', status: 'FIXED' },
  { id: 'R-007', cat: 'RUCKS', complaint: 'There is no dead ball for ages at a time.', cause: 'Ruck timers stack with stoppages.', fix: 'Dead ball is capped at four seconds and restart choreography overlaps with the score card.', inGame: 'Dead-ball cap.', status: 'FIXED' },
  { id: 'R-008', cat: 'RUCKS', complaint: 'You cannot see the ball in the ruck.', cause: 'Ball hidden under bodies.', fix: 'The ball marker is drawn on top of the ruck at its true position at all times.', inGame: 'Always-visible ball marker.', status: 'FIXED' },
  { id: 'R-009', cat: 'RUCKS', complaint: 'Rucks form wherever, with players standing around them.', cause: 'No ruck structure definition.', fix: 'A ruck has a defined gate, an offside line per side, and a maximum of six participants.', inGame: 'Ruck geometry model.', status: 'FIXED' },
  { id: 'R-010', cat: 'RUCKS', complaint: 'Slow ball every time, no matter what I do.', cause: 'Ruck speed independent of clearout quality.', fix: 'Ruck speed is a direct function of clearout quality and numbers. Good play is rewarded visibly.', inGame: 'Clearout-quality ruck speed.', status: 'FIXED' },
  { id: 'R-011', cat: 'RUCKS', complaint: 'Counter-rucking does nothing.', cause: 'No counter-ruck mechanic.', fix: 'Counter-rucking is a deliberate choice: commit two or more early to blow through the gate and win the penalty.', inGame: 'Counter-ruck commit option.', status: 'FIXED' },
  { id: 'R-012', cat: 'RUCKS', complaint: 'The offside line at the ruck is invisible.', cause: 'Not drawn.', fix: 'Both offside lines are drawn in world space the moment the ruck forms, in team colours.', inGame: 'World-space offside lines.', status: 'FIXED' },
  { id: 'R-013', cat: 'RUCKS', complaint: 'Offside penalties against me when I am attacking.', cause: 'Offside tested on all players including those behind the play in their own half.', fix: 'Offside is only tested on players ahead of the ball and inside the relevant half. Attackers behind the play are exempt.', inGame: 'Directional offside test.', status: 'FIXED' },
  { id: 'R-014', cat: 'RUCKS', complaint: 'My player is automatically placed offside when I take possession.', cause: 'Possession snaps the player to a spot past the offside line.', fix: 'Possession never moves a player. He plays the ball from where he legally stands.', inGame: 'No-snap possession.', status: 'FIXED' },
  { id: 'R-015', cat: 'RUCKS', complaint: 'Hands in the ruck is called constantly.', cause: 'Any player near the ball can trigger it.', fix: 'Only a player arriving ahead of the ball from an offside position can be penalised for hands.', inGame: 'Arrival-position legality test.', status: 'FIXED' },
  { id: 'R-016', cat: 'RUCKS', complaint: 'The ruck clock feels arbitrary.', cause: 'A fixed global timer.', fix: 'Ruck clock is a setting — 1.5, 3.0 or 5.0 seconds — and the countdown is drawn on the pitch.', inGame: 'Configurable, visible ruck clock.', status: 'FIXED' },
  { id: 'R-017', cat: 'RUCKS', complaint: 'Mauls are pretty awful and unreadable.', cause: 'Maul force is invisible.', fix: 'Both forces are drawn as kN bars with a live metres-per-second readout and a stall clock.', inGame: 'Maul telemetry.', status: 'FIXED' },
  { id: 'R-018', cat: 'RUCKS', complaint: 'You cannot transfer the ball to the back of the maul.', cause: 'No ball-rank mechanic.', fix: 'The ball rank is shown and can be moved to the tail deliberately to protect it.', inGame: 'Maul ball-rank control.', status: 'FIXED' },
  { id: 'R-019', cat: 'RUCKS', complaint: 'The maul gets turned over with no warning.', cause: 'Stall rule not surfaced.', fix: 'The stall clock is drawn on the pitch with the law threshold, and the referee warns once before whistling.', inGame: 'Maul stall clock with warning.', status: 'FIXED' },
  { id: 'R-020', cat: 'RUCKS', complaint: 'Rucks take too long overall.', cause: 'Resolution timer plus animation plus distribution delay.', fix: 'Quick ball is available in 0.5 seconds and the whole breakdown resolves inside 2.5 seconds.', inGame: 'Hard caps on breakdown duration.', status: 'FIXED' },

  /* ---------------- SCRUMS ---------------- */
  { id: 'S-001', cat: 'SCRUMS', complaint: 'Scrums — what am I supposed to do?', cause: 'No instruction at the point of play.', fix: 'The command is printed on the pitch in plain language at every stage, synchronised to the referee cadence.', inGame: 'On-screen scrum commands.', status: 'FIXED' },
  { id: 'S-002', cat: 'SCRUMS', complaint: 'The timing gauge is not synced with the referee\'s instructions.', cause: 'Meter timer independent of the cadence sequence.', fix: 'The meter is driven by the cadence itself. There is no independent timer to fall out of sync.', inGame: 'Cadence-driven scrum meter.', status: 'FIXED' },
  { id: 'S-003', cat: 'SCRUMS', complaint: 'The bar is impossible to see.', cause: 'Small, low-contrast, in a corner.', fix: 'The bar is drawn on the pitch at the scrum, is wide, colour-banded and duplicated as text.', inGame: 'In-world scrum meter.', status: 'FIXED' },
  { id: 'S-004', cat: 'SCRUMS', complaint: 'Scrums look like a bunch of players fondling each other.', cause: 'Bind geometry is wrong — packs face the wrong way or stand apart.', fix: 'The tunnel runs across the pitch, packs bind face to face, and eight men per side occupy the correct rows.', inGame: 'Correct scrum geometry and binding.', status: 'FIXED' },
  { id: 'S-005', cat: 'SCRUMS', complaint: 'You lose every scrum no matter what you do.', cause: 'Outcome weighted to the CPU or to a hidden stat.', fix: 'Outcome is a legible rating contest plus your input. A dominant pack wins, a weak one loses, and the meter tells you which you are.', inGame: 'Legible scrum contest.', status: 'FIXED' },
  { id: 'S-006', cat: 'SCRUMS', complaint: 'The waggle wrecks your controller and your wrist.', cause: 'Manual waggling is mandatory.', fix: 'Manual waggle is an option, off by default. Auto-push is available and only slightly worse than a good manual effort.', inGame: 'Scrum waggle toggle.', status: 'FIXED' },
  { id: 'S-007', cat: 'SCRUMS', complaint: 'Scrums take too long and kill the pace.', cause: 'Full cadence plus a long drive phase every time.', fix: 'The cadence can be shortened and the drive phase is capped at 2.1 seconds.', inGame: 'Cadence length option, drive cap.', status: 'FIXED' },
  { id: 'S-008', cat: 'SCRUMS', complaint: 'The scrum collapses for no reason.', cause: 'Random collapse roll.', fix: 'Collapse risk is a function of the force differential and both packs\' stability. It is displayed before it happens.', inGame: 'Visible collapse risk model.', status: 'FIXED' },
  { id: 'S-009', cat: 'SCRUMS', complaint: 'You cannot choose to wheel or strike.', cause: 'One generic shove.', fix: 'Four scrum agendas: eight-man shove, wheel for it, strike-heavy, five-three split.', inGame: 'Scrum agenda selection.', status: 'FIXED' },
  { id: 'S-010', cat: 'SCRUMS', complaint: 'The number eight never breaks off the base.', cause: 'No pick-up from the scrum base.', fix: 'The eight can control at the base and either go himself or feed the nine.', inGame: 'Eight-nine off the scrum set play.', status: 'FIXED' },
  { id: 'S-011', cat: 'SCRUMS', complaint: 'Penalties at the scrum are random.', cause: 'No attribution.', fix: 'Every scrum penalty names the offence and the offending shirt number.', inGame: 'Attributed scrum penalties.', status: 'FIXED' },
  { id: 'S-012', cat: 'SCRUMS', complaint: 'Reset scrums loop forever.', cause: 'No reset cap.', fix: 'Two resets maximum, then a free kick to whichever side did not cause them.', inGame: 'Reset cap.', status: 'FIXED' },

  /* ---------------- LINEOUTS ---------------- */
  { id: 'L-001', cat: 'LINEOUTS', complaint: 'You cannot compete at the lineout.', cause: 'Outcome is a coin flip with no input.', fix: 'You call the throw, time the release against a legible band, and the lifter and jumper both animate.', inGame: 'Player-contested lineout.', status: 'FIXED' },
  { id: 'L-002', cat: 'LINEOUTS', complaint: 'The throw is a lottery.', cause: 'Meter timing is arbitrary and unshown.', fix: 'The band is wide, drawn on the pitch, and the sweet spot is marked. The result is a direct function of where you stop.', inGame: 'Legible throw meter.', status: 'FIXED' },
  { id: 'L-003', cat: 'LINEOUTS', complaint: 'Janky lift animations ruin the immersion.', cause: 'Lifter and jumper animations are independent.', fix: 'Lifter drive and jumper extension are keyed to the same timeline so the lift reads as one movement.', inGame: 'Synchronised lift timeline.', status: 'FIXED' },
  { id: 'L-004', cat: 'LINEOUTS', complaint: 'The lineout forms in the wrong place.', cause: 'Mark placed at the ball rather than where it crossed touch.', fix: 'The mark is where the ball crossed touch, between five and fifteen metres in, and the line forms a metre apart.', inGame: 'Correct lineout placement.', status: 'FIXED' },
  { id: 'L-005', cat: 'LINEOUTS', complaint: 'Not straight is called randomly.', cause: 'Independent roll.', fix: 'Not straight is a direct function of how far your throw deviated from the call.', inGame: 'Deviation-driven throw legality.', status: 'FIXED' },
  { id: 'L-006', cat: 'LINEOUTS', complaint: 'You cannot choose a front, middle or tail ball.', cause: 'One throw type.', fix: 'Four calls: front, middle and drive, off the top, tail. Plus a miss-and-peel option.', inGame: 'Lineout call table.', status: 'FIXED' },
  { id: 'L-007', cat: 'LINEOUTS', complaint: 'The lineout drive is impossible to stop.', cause: 'Maul force unbalanced.', fix: 'Defence can sack the jumper on landing or commit to the drive, both with visible force bars.', inGame: 'Lineout drive counter.', status: 'FIXED' },
  { id: 'L-008', cat: 'LINEOUTS', complaint: 'The hooker throws from the wrong place.', cause: 'Thrower positioned on the pitch rather than outside the line.', fix: 'The thrower stands two metres outside the line of touch.', inGame: 'Correct thrower placement.', status: 'FIXED' },
  { id: 'L-009', cat: 'LINEOUTS', complaint: 'Peeling is not in the game.', cause: 'No peel mechanic.', fix: 'Miss-and-peel is a callable option that sets the maul moving before contact.', inGame: 'Miss-and-peel call.', status: 'FIXED' },
  { id: 'L-010', cat: 'LINEOUTS', complaint: 'A softlock at a lineout forces a restart.', cause: 'State machine can stall waiting on an arrival.', fix: 'Assembly state has a hard two-second cap. The set piece begins whether or not everyone has arrived.', inGame: 'Assembly cap; no stall is possible.', status: 'FIXED' },

  /* ---------------- KICKING ---------------- */
  { id: 'K-001', cat: 'KICKING', complaint: 'All aspects of kicking are shocking.', cause: 'One kick verb with an opaque power meter.', fix: 'Five kick verbs, each with an aim line, a landing ellipse, a readable power bar and a stated success probability.', inGame: 'Five-verb kick model with full telemetry.', status: 'FIXED' },
  { id: 'K-002', cat: 'KICKING', complaint: 'A slight joystick wobble completely depletes the power.', cause: 'Power read continuously from the stick.', fix: 'Power is set by two discrete presses and is never affected by subsequent movement. Aim is locked once set.', inGame: 'Discrete kick meter.', status: 'FIXED' },
  { id: 'K-003', cat: 'KICKING', complaint: 'Goal kicking is ridiculously difficult.', cause: 'Twitch timing plus unshown angle and distance.', fix: 'Distance, angle and live probability are all displayed before you commit, and accuracy is gated by the kicker rating.', inGame: 'Goal kick telemetry.', status: 'FIXED' },
  { id: 'K-004', cat: 'KICKING', complaint: 'The kicker changes at random.', cause: 'Kicker selected by proximity.', fix: 'The designated goal kicker, chosen on the squad sheet, takes every goal kick.', inGame: 'Designated kicker.', status: 'FIXED' },
  { id: 'K-005', cat: 'KICKING', complaint: 'You cannot see the ten behind the play to kick with him.', cause: 'Camera frames the ball only.', fix: 'Camera framing includes the ball plus the first three attackers, so the ten is always on screen.', inGame: 'Framing target includes the first receiver.', status: 'FIXED' },
  { id: 'K-006', cat: 'KICKING', complaint: 'When you are close to touch it makes you kick to the other side.', cause: 'Kick direction snapped to a fixed cone.', fix: 'Aim is continuous and shown as a line plus a landing ellipse you steer.', inGame: 'Continuous kick aim.', status: 'FIXED' },
  { id: 'K-007', cat: 'KICKING', complaint: 'The grubber has no control.', cause: 'One rolling kick with fixed velocity.', fix: 'Tap for a short rolling kick, hold for a low driving kick. Length and roll are both yours.', inGame: 'Two-mode grubber.', status: 'FIXED' },
  { id: 'K-008', cat: 'KICKING', complaint: 'The bomb is always regathered by the AI.', cause: 'Contest resolution ignores the chasers.', fix: 'Regather is a contest between your assigned chasers and their receiver, weighted by the chase slider.', inGame: 'Chase-weighted bomb contest.', status: 'FIXED' },
  { id: 'K-009', cat: 'KICKING', complaint: 'The wind does nothing.', cause: 'Wind is cosmetic.', fix: 'Wind pushes the ball off line on every kick and restart, and its strength is displayed on the HUD.', inGame: 'Wind model with HUD readout.', status: 'FIXED' },
  { id: 'K-010', cat: 'KICKING', complaint: 'You cannot kick a drop goal when it matters.', cause: 'Drop goal requires frame-perfect timing.', fix: 'The drop goal is gated by kicker rating and distance, not by a twitch window. Probability is shown first.', inGame: 'Rating-gated drop goal.', status: 'FIXED' },
  { id: 'K-011', cat: 'KICKING', complaint: 'The 50:22 gives the lineout to the other side.', cause: 'Law implemented backwards.', fix: 'A 50:22 gives the throw to the side that kicked it. The target band is drawn on the pitch.', inGame: 'Correct 50:22 law with a drawn target band.', status: 'FIXED' },
  { id: 'K-012', cat: 'KICKING', complaint: 'Conversions are taken from the wrong place.', cause: 'Kick origin defaulted to the posts.', fix: 'The conversion is taken from in line with where the ball was grounded, which is shown before you kick.', inGame: 'Correct conversion placement.', status: 'FIXED' },
  { id: 'K-013', cat: 'KICKING', complaint: 'The kick charge-down is random.', cause: 'No charge-down geometry.', fix: 'A defender inside 1.5 m of the kick origin on the line to goal may charge it down, and it is telegraphed.', inGame: 'Charge-down geometry.', status: 'FIXED' },
  { id: 'K-014', cat: 'KICKING', complaint: 'The ball never goes into touch when you want it to.', cause: 'Touch detection only on the ball crossing the plane.', fix: 'The predicted touch point is drawn before you kick, with the metres gained stated.', inGame: 'Touch prediction line.', status: 'FIXED' },

  /* ---------------- TACKLING ---------------- */
  { id: 'T-001', cat: 'TACKLING', complaint: 'The tackling system is weird and random.', cause: 'One tackle verb with a large non-physical hit sphere.', fix: 'Two tackle verbs — a diving tackle at range and a smother tackle up close — with an honest, displayed contact radius.', inGame: 'Two-verb tackle model with honest ranges.', status: 'FIXED' },
  { id: 'T-002', cat: 'TACKLING', complaint: 'You get dragged back by players who are feet away.', cause: 'Grab radius far exceeds visual contact.', fix: 'Contact radius is 1.1 m and is drawn under the carrier. Nothing outside it can touch you.', inGame: 'Honest contact radius, visualised.', status: 'FIXED' },
  { id: 'T-003', cat: 'TACKLING', complaint: 'Tackle animation warping — players teleport into the tackle.', cause: 'Solver snaps the tackler to the carrier.', fix: 'The tackler must physically arrive. No snapping, ever. Missed tackles look like missed tackles.', inGame: 'No-snap tackling.', status: 'FIXED' },
  { id: 'T-004', cat: 'TACKLING', complaint: 'You cannot choose to go high or low.', cause: 'One tackle height.', fix: 'Smother is low and safe, dive is high-risk and can be penalised. Height is your choice, and the law applies.', inGame: 'Height choice with lawful consequences.', status: 'FIXED' },
  { id: 'T-005', cat: 'TACKLING', complaint: 'The fend does nothing.', cause: 'No fend verb.', fix: 'Fend is a strength contest that wins the collision and keeps the legs moving, on its own button.', inGame: 'Fend verb.', status: 'FIXED' },
  { id: 'T-006', cat: 'TACKLING', complaint: 'Broken tackles are unrealistic — everyone breaks them.', cause: 'Break chance is a flat constant.', fix: 'Break chance is a strength-versus-grip contest modified by the angle of entry and the carrier\'s momentum.', inGame: 'Contest-based tackle break.', status: 'FIXED' },
  { id: 'T-007', cat: 'TACKLING', complaint: 'Nobody can stop the big winger.', cause: 'No gang tackle.', fix: 'Up to three tacklers can bind, and the third always brings him down.', inGame: 'Gang tackle up to three.', status: 'FIXED' },
  { id: 'T-008', cat: 'TACKLING', complaint: 'The tackle is made but play does not stop or the ball spills.', cause: 'Tackle state has no clean transition to the breakdown.', fix: 'The tackle resolves into a defined breakdown with a placed ball, a ruck clock and assigned clearers.', inGame: 'Tackle-to-breakdown pipeline.', status: 'FIXED' },
  { id: 'T-009', cat: 'TACKLING', complaint: 'Late tackles on the kicker are not called.', cause: 'No post-kick protection.', fix: 'Any contact after the kick has gone is a penalty, and the kicker\'s availability drops.', inGame: 'Late tackle law.', status: 'FIXED' },
  { id: 'T-010', cat: 'TACKLING', complaint: 'You cannot tell which of your players can make the tackle.', cause: 'No tackle-range indication.', fix: 'The eligible tackler is highlighted with a range ring showing exactly how far the dive reaches.', inGame: 'Tackle range ring.', status: 'FIXED' },
  { id: 'T-011', cat: 'TACKLING', complaint: 'Defenders stop dead when the carrier steps.', cause: 'Defenders commit to a position with no recovery.', fix: 'Defenders recover from a beat within 0.6 s and re-pursue, so a step buys space rather than a free run.', inGame: 'Defender recovery.', status: 'FIXED' },
  { id: 'T-012', cat: 'TACKLING', complaint: 'Held up in goal gives the defence a drop out instead of a five-metre scrum.', cause: 'Law implemented incorrectly.', fix: 'Held up in the in-goal is a five-metre scrum to the attacking side.', inGame: 'Correct in-goal law.', status: 'FIXED' },

  /* ---------------- LAWS & REFEREE ---------------- */
  { id: 'W-001', cat: 'LAWS & REFEREE', complaint: 'Penalties that do not seem to make any sense.', cause: 'Unattributed random penalty rolls.', fix: 'Every penalty names the law, the offending team and the shirt number, and is accompanied by a signal animation.', inGame: 'Attributed penalty model.', status: 'FIXED' },
  { id: 'W-002', cat: 'LAWS & REFEREE', complaint: 'There is no offside at all — players stand in front of the ball.', cause: 'Offside law disabled or untested.', fix: 'Offside is on by default, tested directionally, and the lines are drawn before the whistle.', inGame: 'Enforced, drawn, directional offside.', status: 'FIXED' },
  { id: 'W-003', cat: 'LAWS & REFEREE', complaint: 'Cards are inconsistent.', cause: 'Card threshold independent of the offence.', fix: 'A card requires either a repeat offence or a high tackle with force. The threshold is a setting.', inGame: 'Card threshold model.', status: 'FIXED' },
  { id: 'W-004', cat: 'LAWS & REFEREE', complaint: 'Advantage is never played.', cause: 'Whistle is immediate.', fix: 'Advantage is played for a configurable window, shown on the HUD, and the referee calls advantage over.', inGame: 'Advantage system.', status: 'FIXED' },
  { id: 'W-005', cat: 'LAWS & REFEREE', complaint: 'The referee does not explain the first call of each type.', cause: 'No onboarding in the laws.', fix: 'The first time each law is applied in a match, a caption states in one line what it was for.', inGame: 'First-call law explanation.', status: 'FIXED' },
  { id: 'W-006', cat: 'LAWS & REFEREE', complaint: 'The referee behaves identically every match.', cause: 'One referee profile.', fix: 'Four referee profiles with different strictness, advantage length and card thresholds.', inGame: 'Referee profiles.', status: 'FIXED' },
  { id: 'W-007', cat: 'LAWS & REFEREE', complaint: 'The mark is not given from a high ball catch.', cause: 'Mark law missing.', fix: 'A clean catch inside your own twenty-two from a kick is a mark and a free kick.', inGame: 'Mark law.', status: 'FIXED' },
  { id: 'W-008', cat: 'LAWS & REFEREE', complaint: 'Knock-ons are called when the ball goes backwards.', cause: 'Knock-on tested on any loose ball.', fix: 'Knock-on is tested against the ball\'s actual vector relative to the attacking direction.', inGame: 'Vector-tested knock-on.', status: 'FIXED' },
  { id: 'W-009', cat: 'LAWS & REFEREE', complaint: 'Obstruction and crossing are never called.', cause: 'No decoy legality test.', fix: 'A decoy runner must stay behind the ball. Crossing is a penalty and is telegraphed before it happens.', inGame: 'Decoy legality model.', status: 'FIXED' },
  { id: 'W-010', cat: 'LAWS & REFEREE', complaint: 'The scrum feed is never penalised for being crooked.', cause: 'No feed law.', fix: 'Feed crookedness is a setting, and a crooked feed is a free kick.', inGame: 'Scrum feed law.', status: 'FIXED' },
  { id: 'W-011', cat: 'LAWS & REFEREE', complaint: 'The TMO is never used.', cause: 'No TMO system.', fix: 'Every try in the corner goes to the TMO with the grounding angle shown, taking four seconds.', inGame: 'TMO check on corner tries.', status: 'DESIGNED_AROUND' },
  { id: 'W-012', cat: 'LAWS & REFEREE', complaint: 'The clock does not stop for injuries.', cause: 'No injury model.', fix: 'Injuries stop the clock and force a substitution, with the injury time added at the end of the half.', inGame: 'Injury and added-time model.', status: 'DESIGNED_AROUND' },

  /* ---------------- FLOW & PACING ---------------- */
  { id: 'F-001', cat: 'FLOW & PACING', complaint: 'It is fast when it should be normal and slow when it should be fast.', cause: 'Animation lengths mismatched to game state.', fix: 'Animation duration is driven by ball availability and phase urgency, never by a fixed clip length.', inGame: 'State-driven animation timing.', status: 'FIXED' },
  { id: 'F-002', cat: 'FLOW & PACING', complaint: 'Everything is so slow you cannot improvise.', cause: 'Global speed throttle plus long transitions.', fix: 'Open play runs at full speed with zero-frame input. Nothing waits for an animation to finish.', inGame: 'No animation gating.', status: 'FIXED' },
  { id: 'F-003', cat: 'FLOW & PACING', complaint: 'Loading between phases.', cause: 'Phase transitions reload a scene.', fix: 'No loading between any two phases. Set pieces assemble in world space from where the players stand.', inGame: 'In-world set-piece assembly.', status: 'FIXED' },
  { id: 'F-004', cat: 'FLOW & PACING', complaint: 'Cut-scenes distract from the game.', cause: 'Full-screen sequences on every score.', fix: 'Score cards are drawn over live play. The match never stops to show you a celebration.', inGame: 'Overlay score cards.', status: 'FIXED' },
  { id: 'F-005', cat: 'FLOW & PACING', complaint: 'Score lines are unrealistic — 70 points a game.', cause: 'Defence too weak and conversions automatic.', fix: 'Expected-points model tuned so a good side scores three to five tries against an equal one.', inGame: 'Expected-points scoring model.', status: 'FIXED' },
  { id: 'F-006', cat: 'FLOW & PACING', complaint: 'There is no sense of momentum in a match.', cause: 'No momentum state.', fix: 'Momentum is tracked and displayed, and it shifts the CPU\'s risk appetite visibly.', inGame: 'Momentum meter.', status: 'FIXED' },
  { id: 'F-007', cat: 'FLOW & PACING', complaint: 'You cannot see how much time is left properly.', cause: 'Clock scaled oddly or hidden.', fix: 'The match clock is always on screen with the half indicator and the added time.', inGame: 'Always-visible clock.', status: 'FIXED' },
  { id: 'F-008', cat: 'FLOW & PACING', complaint: 'The last five minutes take forever.', cause: 'Every stoppage fully choreographed.', fix: 'Dead ball capped at four seconds and restarts overlap with the score card.', inGame: 'Dead-ball cap.', status: 'FIXED' },
  { id: 'F-009', cat: 'FLOW & PACING', complaint: 'No set plays at all — even 1990s games had them.', cause: 'Set plays never implemented.', fix: 'Ten callable set plays across ruck, scrum and lineout, each with named runner instructions.', inGame: 'Set-play library.', status: 'FIXED' },
  { id: 'F-010', cat: 'FLOW & PACING', complaint: 'You cannot take a quick tap from a penalty.', cause: 'Penalty always stops play.', fix: 'A quick tap is available instantly with one button, and the defence must be ten metres back.', inGame: 'Quick tap.', status: 'FIXED' },
  { id: 'F-011', cat: 'FLOW & PACING', complaint: 'You cannot take a quick lineout.', cause: 'Lineout always fully forms.', fix: 'A quick lineout is offered if the ball is dead and a support is within five metres.', inGame: 'Quick lineout.', status: 'DESIGNED_AROUND' },
  { id: 'F-012', cat: 'FLOW & PACING', complaint: 'The game feels heavy, bloated and slow overall.', cause: 'Too many systems gating every action.', fix: 'One verb per intent, one frame of latency, and no system between the press and the outcome.', inGame: 'Single-path input pipeline.', status: 'FIXED' },

  /* ---------------- CAMERA & FEEDBACK ---------------- */
  { id: 'C-001', cat: 'CAMERA & FEEDBACK', complaint: 'The camera is too tight to see the support.', cause: 'Camera tracks the ball only.', fix: 'Framing target is the ball plus the first three attackers and the nearest three defenders.', inGame: 'Group framing target.', status: 'FIXED' },
  { id: 'C-002', cat: 'CAMERA & FEEDBACK', complaint: 'You cannot tell which player you are controlling.', cause: 'No controlled-player indication.', fix: 'Name plate, shirt number, arrow and a distinct ring under the boots.', inGame: 'Four-channel controlled-player indicator.', status: 'FIXED' },
  { id: 'C-003', cat: 'CAMERA & FEEDBACK', complaint: 'The radar is useless or absent.', cause: 'Minimap not drawn or not informative.', fix: 'A transparent pitch map with hollow player dots, a solid ball, the camera frustum and the attacking direction.', inGame: 'Full tactical radar.', status: 'FIXED' },
  { id: 'C-004', cat: 'CAMERA & FEEDBACK', complaint: 'You cannot see the direction of play.', cause: 'Camera direction ambiguous.', fix: 'The camera never orbits; the attacking direction is always up-field, and an arrow states it.', inGame: 'Fixed-axis camera plus direction arrow.', status: 'FIXED' },
  { id: 'C-005', cat: 'CAMERA & FEEDBACK', complaint: 'Player ratings and stats are hidden.', cause: 'No stats surface.', fix: 'A live statistics panel and a squad sheet with six rated attributes per player.', inGame: 'Live stats and rated squads.', status: 'FIXED' },
  { id: 'C-006', cat: 'CAMERA & FEEDBACK', complaint: 'You never know how tired your players are.', cause: 'Fatigue hidden.', fix: 'Live per-player fatigue, shown in the pause menu and on the squad sheet.', inGame: 'Visible fatigue.', status: 'FIXED' },
  { id: 'C-007', cat: 'CAMERA & FEEDBACK', complaint: 'Replays are unskippable.', cause: 'Replay auto-plays.', fix: 'Replays are skippable with any button and are never forced except on a try, where they are also skippable.', inGame: 'Skippable replays.', status: 'FIXED' },
  { id: 'C-008', cat: 'CAMERA & FEEDBACK', complaint: 'The HUD tells you nothing about the state of play.', cause: 'Sparse HUD.', fix: 'Four HUD densities, from bare score to full telemetry with expected points.', inGame: 'HUD density setting.', status: 'FIXED' },
  { id: 'C-009', cat: 'CAMERA & FEEDBACK', complaint: 'You cannot zoom out to see the shape.', cause: 'Fixed camera.', fix: 'Mouse wheel zoom pulls the rig back and up into a tactical top-down view.', inGame: 'Continuous camera zoom.', status: 'FIXED' },
  { id: 'C-010', cat: 'CAMERA & FEEDBACK', complaint: 'The camera cuts disorient you between phases.', cause: 'Hard cuts on phase change.', fix: 'Phase changes are masked by a wipe and the camera dollies rather than cutting where possible.', inGame: 'Wipe-masked phase transitions.', status: 'FIXED' },

  /* ---------------- CONTROLS ---------------- */
  { id: 'I-001', cat: 'CONTROLS', complaint: 'The controls are far too complex.', cause: 'Too many stacked modifiers.', fix: 'One verb per button, no modifiers except the dummy, and a single-button mode for complete beginners.', inGame: 'Clean verb map plus single-button mode.', status: 'FIXED' },
  { id: 'I-002', cat: 'CONTROLS', complaint: 'Fending and sidestepping on an analogue stick is stupid.', cause: 'Directional flicks for actions.', fix: 'Step and fend are discrete buttons, not stick gestures.', inGame: 'Discrete step and fend buttons.', status: 'FIXED' },
  { id: 'I-003', cat: 'CONTROLS', complaint: 'You cannot remap anything.', cause: 'Hard-bound controls.', fix: 'Every verb is rebindable, including on keyboard.', inGame: 'Full remap.', status: 'FIXED' },
  { id: 'I-004', cat: 'CONTROLS', complaint: 'The tutorial crashes or is useless.', cause: 'Tutorial built as a separate fragile mode.', fix: 'The skill zone is the same engine in a loop, with seven drills that cannot crash because they cannot end.', inGame: 'In-engine skill zone.', status: 'FIXED' },
  { id: 'I-005', cat: 'CONTROLS', complaint: 'There is no explanation of rugby itself.', cause: 'No laws reference in game.', fix: 'A media guide with every law in one line each, plus a first-call explanation during play.', inGame: 'Laws reference and first-call captions.', status: 'FIXED' },
  { id: 'I-006', cat: 'CONTROLS', complaint: 'Sprint feels like a different game to jogging.', cause: 'Two disjoint speed states.', fix: 'Sprint is a continuous ramp on one curve over half a second.', inGame: 'Continuous speed curve.', status: 'FIXED' },
  { id: 'I-007', cat: 'CONTROLS', complaint: 'Momentum overrides my input and I run weird shapes.', cause: 'Pre-baked running paths.', fix: 'Movement is sampled every frame and applied immediately. There are no pre-baked paths.', inGame: 'Frame-sampled movement, no paths.', status: 'FIXED' },
  { id: 'I-008', cat: 'CONTROLS', complaint: 'Defending is random and you have little control.', cause: 'Defender switching is automatic and unpredictable.', fix: 'Defender switching is explicit, cycles the nearest three, and the eligible tackler is highlighted.', inGame: 'Explicit defender switching.', status: 'FIXED' },
  { id: 'I-009', cat: 'CONTROLS', complaint: 'You cannot control the kicker and the chaser separately.', cause: 'One controlled player at a time with no hand-off.', fix: 'While a kick is in flight you control a chaser; the switch is automatic and stated on screen.', inGame: 'Chaser hand-off.', status: 'FIXED' },
  { id: 'I-010', cat: 'CONTROLS', complaint: 'There is no assist for beginners.', cause: 'One difficulty of input precision.', fix: 'Pass, tackle and kick assist are each adjustable from full to off, independently of the AI difficulty.', inGame: 'Three assist sliders.', status: 'FIXED' },

  /* ---------------- PROGRESSION ---------------- */
  { id: 'G-001', cat: 'PROGRESSION', complaint: 'Team management does not save between matches.', cause: 'No persistence layer.', fix: 'Squad order, tactics, formations and kicker are all persisted to the profile and restored.', inGame: 'Profile persistence.', status: 'FIXED' },
  { id: 'G-002', cat: 'PROGRESSION', complaint: 'Substitutions made at half time did not go through.', cause: 'Sub applied to a stale roster.', fix: 'Substitutions apply immediately to the live roster and are confirmed on screen.', inGame: 'Immediate, confirmed substitutions.', status: 'FIXED' },
  { id: 'G-003', cat: 'PROGRESSION', complaint: 'Career mode is a spreadsheet with no feedback.', cause: 'No reporting.', fix: 'Every match produces a report card: three deciding moments, five player ratings and a man of the match.', inGame: 'Match report card.', status: 'FIXED' },
  { id: 'G-004', cat: 'PROGRESSION', complaint: 'There is nothing to work towards.', cause: 'No unlocks.', fix: 'Two all-star sides, a classic-match ladder of twelve scenarios and a skill-zone medal set.', inGame: 'Unlock ladder.', status: 'FIXED' },
  { id: 'G-005', cat: 'PROGRESSION', complaint: 'The draw and the tables are wrong.', cause: 'Competition model hand-waved.', fix: 'Authentic pools, a circle-method round robin, correct tiebreakers on points difference then points for.', inGame: 'Correct competition model.', status: 'FIXED' },
  { id: 'G-006', cat: 'PROGRESSION', complaint: 'Simulated results make no sense.', cause: 'Random scores.', fix: 'Simulated scores are drawn from a Poisson model around the rating differential, producing realistic margins.', inGame: 'Rating-based result simulation.', status: 'FIXED' },
  { id: 'G-007', cat: 'PROGRESSION', complaint: 'There is no multiplayer.', cause: 'No second player support.', fix: 'Two players, one keyboard, either head to head or sharing a side.', inGame: 'Two-player mode.', status: 'FIXED' },

  /* ---------------- AUDIO & ATMOSPHERE ---------------- */
  { id: 'U-001', cat: 'AUDIO & ATMOSPHERE', complaint: 'Zero atmosphere in the stadiums.', cause: 'One crowd loop at constant volume.', fix: 'Crowd is mixed from the travelling support ratio and swells with field position and momentum.', inGame: 'Position-weighted crowd mix.', status: 'DESIGNED_AROUND' },
  { id: 'U-002', cat: 'AUDIO & ATMOSPHERE', complaint: 'A single person shouting come on England.', cause: 'No crowd sample variety.', fix: 'Layered terrace noise that reacts to the half, the score and the occasion.', inGame: 'Reactive crowd layers.', status: 'DESIGNED_AROUND' },
  { id: 'U-003', cat: 'AUDIO & ATMOSPHERE', complaint: 'No chants, no haka, no life.', cause: 'Not implemented.', fix: 'Pre-match occasion card naming the fixture, the crowd split and the trophy at stake.', inGame: 'Occasion presentation.', status: 'DESIGNED_AROUND' },
  { id: 'U-004', cat: 'AUDIO & ATMOSPHERE', complaint: 'The commentators name players who are not even in the match.', cause: 'Commentary strings use the wrong roster index.', fix: 'Commentary is generated from the live player object that performed the action. It cannot name the wrong man.', inGame: 'Action-attributed commentary.', status: 'FIXED' },
  { id: 'U-005', cat: 'AUDIO & ATMOSPHERE', complaint: 'The commentary says the opposite of what happened.', cause: 'Commentary triggered by the wrong event.', fix: 'Every commentary line is keyed to a single unambiguous event with the parameters passed in.', inGame: 'Event-parameterised commentary.', status: 'FIXED' },
  { id: 'U-006', cat: 'AUDIO & ATMOSPHERE', complaint: 'The commentary repeats constantly.', cause: 'A pool of a dozen lines.', fix: 'A bank of ninety lines in a two-hander register, with a no-repeat window and situational prioritisation.', inGame: 'Two-hander commentary bank.', status: 'FIXED' },
  { id: 'U-007', cat: 'AUDIO & ATMOSPHERE', complaint: 'The referee gives no verbal cadence.', cause: 'Silent scrum sequence.', fix: 'The scrum cadence is printed as the referee calls it and drives the meter directly.', inGame: 'Visible referee cadence.', status: 'DESIGNED_AROUND' },

  /* ---------------- STABILITY ---------------- */
  { id: 'X-001', cat: 'STABILITY', complaint: 'The first two matches crashed.', cause: 'Uncontrolled state transitions.', fix: 'Every phase transition passes through one guarded switch with a validated state. Illegal states self-heal to open play.', inGame: 'Guarded state machine with self-healing.', status: 'FIXED' },
  { id: 'X-002', cat: 'STABILITY', complaint: 'Softlocked at a lineout, had to quit the match.', cause: 'A phase waiting on an arrival that never completes.', fix: 'Every assembly has a hard cap. No phase can wait more than two seconds for anything.', inGame: 'Universal assembly cap.', status: 'FIXED' },
  { id: 'X-003', cat: 'STABILITY', complaint: 'No dead ball until minute seventy-five after pausing.', cause: 'Clock and phase timers desynchronise on pause.', fix: 'Pausing halts every timer in the match, including all phase clocks, and they resume together.', inGame: 'Unified pause.', status: 'FIXED' },
  { id: 'X-004', cat: 'STABILITY', complaint: 'Players freeze in place after a phase change.', cause: 'Targets not reassigned on transition.', fix: 'Targets are reassigned every frame for all thirty players. There is no such thing as an unassigned player.', inGame: 'Per-frame target assignment.', status: 'FIXED' },
  { id: 'X-005', cat: 'STABILITY', complaint: 'The ball disappears.', cause: 'Ball ownership undefined at a transition.', fix: 'The ball has exactly one owner or one physics state at all times, asserted every frame.', inGame: 'Single-owner ball model.', status: 'FIXED' },

  /* ---------------- ACCEPTED LIMITATIONS ---------------- */
  { id: 'Z-001', cat: 'STABILITY', complaint: 'It is not a full simulation of the laws.', cause: 'Scope.', fix: 'Twenty-five laws are modelled. The remaining laws of the game are out of scope for a 16-bit-styled engine.', inGame: 'Laws reference states exactly which are modelled.', status: 'ACCEPTED' },
  { id: 'Z-002', cat: 'AUDIO & ATMOSPHERE', complaint: 'There is no spoken commentary audio.', cause: 'No audio pipeline in this build.', fix: 'Commentary is delivered as a two-line caption pair in the McLaren and Beaumont register.', inGame: 'Caption commentary.', status: 'ACCEPTED' },
  { id: 'Z-003', cat: 'PROGRESSION', complaint: 'There is no multi-season career.', cause: 'Scope.', fix: 'Four competition structures plus a classic-match ladder and a skill zone.', inGame: 'Competition model.', status: 'ACCEPTED' },
  { id: 'Z-004', cat: 'AI SHAPE', complaint: 'Players do not have individual running animations.', cause: 'One rig, one clip library.', fix: 'Per-actor phase offsets, fatigue drift and speed-driven clip selection so no two players animate alike.', inGame: 'Per-actor animation variation.', status: 'ACCEPTED' },
  { id: 'Z-005', cat: 'CONTROLS', complaint: 'No online play.', cause: 'No netcode in this build.', fix: 'Two players on one keyboard.', inGame: 'Local multiplayer.', status: 'ACCEPTED' },
  { id: 'Z-006', cat: 'FLOW & PACING', complaint: 'Not every real set-piece variation is available.', cause: 'Scope.', fix: 'Thirty formations across six categories and ten set plays cover the great majority of what is actually used.', inGame: 'Formation and set-play libraries.', status: 'ACCEPTED' },
];

export const PITFALL_COUNT = PITFALLS.length;

export function pitfallPoints(): { total: number; byCategory: Array<[string, number, number]>; byStatus: Array<[string, number]> } {
  const cats = new Map<string, { total: number; fixed: number }>();
  for (const p of PITFALLS) {
    const c = cats.get(p.cat) ?? { total: 0, fixed: 0 };
    c.total++;
    if (p.status === 'FIXED') c.fixed++;
    cats.set(p.cat, c);
  }
  const statuses = new Map<string, number>();
  for (const p of PITFALLS) statuses.set(p.status, (statuses.get(p.status) ?? 0) + 1);
  return {
    total: PITFALLS.length * 6,
    byCategory: [...cats.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([k, v]) => [k, v.total, v.fixed] as [string, number, number]),
    byStatus: [...statuses.entries()].map(([k, v]) => [k, v] as [string, number]),
  };
}

/** Search index used by the in-game registry screen. */
export function searchPitfalls(q: string): Pitfall[] {
  const s = q.trim().toLowerCase();
  if (!s) return PITFALLS;
  return PITFALLS.filter((p) =>
    (p.complaint + p.cause + p.fix + p.cat + p.inGame).toLowerCase().includes(s));
}
