import { mkLines, RunLine } from './lines';

// ===== 6 BLINDSIDE FLANKER =====
const a6 = mkLines(6, 'attack', [
  ['Edge forward overs line', 'Overs', 'ruck',
    'You are the last forward before the backs and the ball is coming your way',
    'Leave on the first pass, arrive as the second pass lands',
    'sprint',
    'Attack the seam outside the last forward defender where their fold is thinnest.',
    'If the edge is stocked, tuck in and become the tail of the middle pod.',
    'A back-rower who folds fast to that seam; counter by attacking one channel wider.',
    [[-7, 11], [-4, 12.5], [-1, 14], [2, 15]]],
  ['Trailing offload arc', 'Support', 'tackle contact',
    'A team-mate breaks the line in front of you',
    'Go the moment he steps; stay 3-5m behind and inside',
    'max',
    'Sit in the offload window so a half-break becomes a full break.',
    'If a back is already in the window, take the outside shoulder instead.',
    'A tackler who wraps the ball arm; counter by supporting on the free-arm side.',
    [[-5, 8], [-2, 11], [1, 14], [4, 17]]],
  ['Maul peel and carry', 'Unders', 'maul',
    'The maul is halted and you are at the back',
    'Break on the second stall, low and quick',
    'cruise',
    'Attack the short seam beside the maul where their guard has been sucked in.',
    'If 8 takes the ball, latch and drive him.',
    'A dedicated maul guard; counter by going the other side or spinning it wide.',
    [[-2, 1], [-0.5, -0.5], [1, -2], [2.5, -3.5]]],
  ['Short-side strike', 'Straight', 'ruck',
    '9 plays blind after two openside phases',
    'Set on the short side as the ruck forms; go on the 9\'s hands',
    'sprint',
    'Get outside the pillar into the 5m channel and put the winger away.',
    'If a prop is holding the short side, run outside him as the second option.',
    'A blindside winger who stays home; counter by using it as a decoy and swinging back.',
    [[-4, -4], [-2, -6], [0, -8], [2, -10]]],
  ['Cleanout wide arc', 'Cleanout', 'tackle contact',
    'The wide breakdown is at risk of being isolated',
    'Leave as the pass goes wide, run the outside-in arc',
    'max',
    'Prevent the edge turnover, the highest-cost breakdown loss in the game.',
    'If two players are already committed, stand up as the touchline-side pillar.',
    'A defence that concedes the ruck and gets set; counter by not over-committing bodies.',
    [[-4, 8], [-2, 12], [-0.5, 15], [0.5, 17]]],
  ['Blind carry hold', 'Unders', 'ruck',
    'The ruck is live and the short side is open',
    'Set as the ruck forms; go on 9\'s first step blind',
    'cruise',
    'Hold the short side 1.2 m outside the box edge, a stride behind the hindmost foot, as the blind carry threat; carry if 9 goes blind.',
    'If the blind is stocked, push out as the +1 outside the pod.',
    'A blind pillar who reads the 9; counter by holding a beat and taking the tip from 8.',
    [[-2.6, -3.4], [-1.4, -3.4], [0, -3.2], [1.6, -3.0]]],
  ['Gate-routed cleanout (blindside)', 'Cleanout', 'ruck',
    'A team-mate is tackled and you are level with or in front of the pile',
    'Depart on contact; flank first, never a straight line through the box (engine/forwardPack.ts routeThroughGate)',
    'sprint',
    'Reach the ball THROUGH THE GATE: out to the open flank clear of the contest box, back behind our hindmost foot, then in through the mouth — the referee\'s ledger records the corridor pass and the entry is lawful.',
    'If a team-mate is already through the gate on the ball, hold the gate mouth as the anchor and stay on your feet.',
    'A defence that shifts the pile sideways onto your flank line; counter by widening the flank by a stride and re-planning, never by cutting the corner.',
    [[0.4, 1.4], [0.4, 2.8], [-2.3, 2.8], [-1.9, 0.6], [-0.6, 0.2]]],
]);
const d6 = mkLines(6, 'defence', [
  ['Wide-channel line speed', 'Blitz', 'ruck',
    'Their pod or first receiver takes the ball in the wide forward channel',
    'Go on the pass, connected, shoulders square',
    'sprint',
    'Cut down the space before their edge play develops and force the pass backwards.',
    'If your outside man shoots, hold and cover his inside shoulder.',
    'A tip-on behind your rush; counter by having the guard stay flat as a lid.',
    [[-3, 10], [-1.5, 10.5], [0, 11], [1.5, 11.5]]],
  ['Post-tackle jackal entry', 'Jackal', 'tackle contact',
    'You or a team-mate complete the tackle and the carrier is isolated',
    'Enter through the gate, feet before hands, within 0.8 seconds',
    'sprint',
    'Win the ball or force the holding-on penalty at the point of contact.',
    'If 7 is already over the ball, become his sealer.',
    'A latched carrier with instant support; counter by only jackaling clean, isolated tackles.',
    [[-2.5, 2], [-1.2, 1], [-0.2, 0.2]]],
  ['Cover arc to touch', 'Shepherd', 'ruck',
    'They break into the wide channel outside you',
    'Turn and run a curve that closes the outside first',
    'max',
    'Herd the carrier back inside into the covering traffic instead of racing his heels.',
    'If the winger already owns the outside, take the inside shoulder line.',
    'A step back inside; counter by keeping your inside foot planted and eyes on his hips.',
    [[-2, 10], [1, 15], [3, 20], [4, 25]]],
  ['Blindside pillar — anchor the line', 'Pillar', 'ruck',
    'Their ruck forms',
    'Round the box if you are in front of it; plant on the hindmost-foot line on the short side',
    'sprint',
    'Pillar the short side: on Law 16\'s line, outside the box edge on the blind, planted — nothing comes back inside you.',
    'If the pillar is taken, take the next channel out.',
    'A wrap play that brings the ball back blind; counter by never drifting off the pillar before the pass.',
    [[-1.0, -2.6], [2.4, -2.6], [3.0, -2.2], [3.0, -2.2]]],
  ['Blindside line anchor (open play)', 'Blitz', 'ruck',
    'Open play with the ball more than 10 m off centre',
    'On every phase; be set before the pass',
    'jog',
    'Anchor the touchline side of the line 3.2 m from the ball; the short side is never left open.',
    'If a back holds the touchline, take the channel inside him.',
    'An attack that overloads the open; counter by trusting the fold and holding the edge.',
    [[0, -3.2], [0.5, -3.2], [1.5, -3.0], [2.5, -2.8]]],
]);

// ===== 7 OPENSIDE FLANKER =====
const a7 = mkLines(7, 'attack', [
  ['Link runner flat line', 'Straight', 'ruck',
    'The pod carries and you are the nearest support',
    'Follow the ball flat, 2m behind and inside the carrier',
    'sprint',
    'Be the tip-on target or the first cleaner, whichever the collision demands.',
    'If a forward is already the link, take the far pod tail.',
    'A defence that jams the tip-on; counter by carrying the tip-on ball yourself.',
    [[-3, 3], [-1, 4], [1, 5], [3, 5.5]]],
  ['First-cleaner sprint arc', 'Cleanout', 'tackle contact',
    'Any tackle is made anywhere within 20m',
    'Leave on contact; you should be first to 80% of breakdowns',
    'max',
    'Guarantee sub-3-second ball by arriving before their jackal is loaded.',
    'If the ball is clearly secure, do not enter — stand up as the pillar.',
    'Defences that send the jackal early; counter by hitting him before he grips.',
    [[-5, -4], [-3, -2], [-1, -0.5], [0.5, 0.4]]],
  ['Second-phase snipe support', 'Unders', 'ruck',
    '9 snipes off the ruck',
    'Set on his inside hip, go on his first step',
    'sprint',
    'Be the inside offload option so the snipe becomes a linebreak, not a tackle.',
    'If another forward is on that hip, take the outside shoulder.',
    'A pillar that reads the snipe; counter by using the snipe as a decoy.',
    [[-2, 1.5], [-0.5, 1], [1, 0.8], [2.5, 1]]],
  ['Wide arc to the edge ruck', 'Support', 'ruck',
    'The ball is swung to the edge',
    'Sprint the arc behind the line the moment the ball leaves 9',
    'max',
    'Arrive at the wide breakdown first so the edge is never isolated.',
    'If two are already there, hold as the pillar to attack back infield.',
    'A defence that concedes the wide ruck and gets set; counter by playing back infield fast.',
    [[-4, 2], [-3, 8], [-1.5, 14], [0, 19]]],
  ['Turnover scoop and go', 'Straight', 'tackle contact',
    'You win the jackal or a loose ball appears',
    'Scoop on the run — never stop to pick up',
    'max',
    'Attack in the two-second window before their defence has re-set.',
    'If a team-mate has the ball, become his immediate inside support.',
    'A defence with a designated counter-jackal; counter by passing before contact.',
    [[0, 0], [2.5, 1.5], [5, 3.5], [8, 6]]],
  ['First support off the base', 'Support', 'ruck',
    'The ruck is live and you are not in its roster',
    'Set two metres behind the hindmost foot; go on 9\'s hands',
    'cruise',
    'Ride the open edge 0.8 m outside the box, two metres behind the line — the first support on every carry, always behind the ball.',
    'If a forward is the link, be the far pod tail.',
    'A defence that shoots the link; counter by staying a beat deeper and taking the inside ball.',
    [[-3.6, 2.4], [-2.4, 2.6], [-0.8, 3.0], [1.0, 3.2]]],
  ['Gate-routed cleanout (openside)', 'Cleanout', 'ruck',
    'A team-mate is tackled and you are level with or in front of the pile',
    'Depart on contact; flank first, never a straight line through the box (engine/forwardPack.ts routeThroughGate)',
    'sprint',
    'Reach the ball THROUGH THE GATE: out to the open flank clear of the contest box, back behind our hindmost foot, then in through the mouth — the referee\'s ledger records the corridor pass and the entry is lawful.',
    'If a team-mate is already through the gate on the ball, hold the gate mouth as the anchor and stay on your feet.',
    'A defence that shifts the pile sideways onto your flank line; counter by widening the flank by a stride and re-planning, never by cutting the corner.',
    [[0.4, 1.4], [0.4, 2.8], [-2.3, 2.8], [-1.9, 0.6], [-0.6, 0.2]]],
]);
const d7 = mkLines(7, 'defence', [
  ['Jackal approach through the gate', 'Jackal', 'tackle contact',
    'A tackle is completed and the carrier is isolated',
    'Arrive within 0.8 seconds, feet first, hands late',
    'max',
    'Win the turnover or the penalty — your single highest-value action.',
    'If another jackal is on the ball, seal him and take the hit.',
    'An instant latch cleanout; counter by attacking the ball from the side of the tackle.',
    [[-4, -3], [-2, -1.5], [-0.6, -0.3], [0, 0]]],
  ['Second-man line hunt', 'Blitz', 'ruck',
    'Ruck formed and you are the second defender off it',
    'Move on the pass, hunting the next tackle to be first to the ball',
    'sprint',
    'Be involved in the tackle so you can immediately contest the ball afterwards.',
    'If 6 has the ruck edge, take the guard slot one wider.',
    'A pod that runs at you with a latch; counter by chopping low and letting 6 contest.',
    [[-2, 3], [-0.5, 4], [1, 5], [2, 6]]],
  ['Broken-field intercept arc', 'Scramble', 'ruck',
    'A line break is made and you are behind the ball',
    'Turn instantly; run to where he will be, not where he is',
    'max',
    'Cut the angle and make the scramble tackle, then contest the isolated ball.',
    'If the fullback has the tackle covered, arc to the support runner instead.',
    'An early offload; counter by taking the support runner instead of the carrier.',
    [[-3, 8], [0, 13], [4, 17], [8, 20]]],
  ['Jackal approach to the defence gate', 'Jackal', 'tackle contact',
    'The carrier is HELD (the latch) — a tackle about to become a ruck',
    'Depart on the latch; be at the defence gate 1.6 m on our side of the carrier the frame the ruck forms',
    'max',
    'Get over the ball legally: arrive through the defence gate, not the side, so the referee\'s ledger records the corridor pass before the volume is entered.',
    'If another jackal is on, seal and protect him.',
    'A cleaner who beats you to the gate; counter by hitting his hip as he arrives, never his back.',
    [[6, 2.0], [3.6, 1.0], [1.6, 0.2], [0.6, 0.0]]],
  ['Hunt the loose ball', 'Jackal', 'tackle contact',
    'A ball is on the deck within 14 m',
    'Immediately; nearest man within 0.8 m takes it, 2.2 s and it goes the other way (engine/ballcraft.ts LOOSE)',
    'max',
    'Be the man on the ball before the ruck forms — the openside\'s whole job.',
    'If a team-mate is closer, be his protector.',
    'A quick pick by their 9; counter by arriving low and square.',
    [[8, 3.0], [5, 2.0], [2, 0.8], [0.4, 0.0]]],
  ['Openside post', 'Pillar', 'ruck',
    'Their ruck is formed and you are not in it',
    'Plant on the line outside the box on the open side; read the 9',
    'sprint',
    'The openside post on the hindmost-foot line: first to the next tackle, first to the next jackal.',
    'If the post is taken, guard one wider.',
    'A pick-and-go at the post; counter by holding low and square.',
    [[-1.0, 2.6], [2.4, 2.6], [3.0, 2.2], [3.0, 2.2]]],
]);

// ===== 8 NUMBER 8 =====
const a8 = mkLines(8, 'attack', [
  ['Pick and go, tight unders', 'Unders', 'ruck',
    'Red zone, or the fringe defender has stood up',
    'Pick on the 9\'s call, low, first step through the pillar seam',
    'cruise',
    'Attack the 1m seam beside the ruck where the defence is weakest and slowest to fold.',
    'If a prop or lock has the pick, be the latch and drive him.',
    'A low double tackle; counter by going once and then spinning it wide.',
    [[-1.5, 0.5], [-0.3, 0.2], [1, 0.3], [2.3, 0.8]]],
  ['Base carry off the scrum', 'Overs', 'scrum base',
    'Scrum is stable and their back row has bound tight',
    'Pick on the ball being controlled, break at the flanker channel',
    'sprint',
    'Attack the seam between their flanker and 9 to get the attack over the gain line.',
    'If their 8 has broken first, release to 9 and become the trailing option.',
    'A back row that breaks early; counter by feeding 9 and going wide.',
    [[0, 0], [1.5, 1.5], [3, 3.2], [4.5, 5]]],
  ['Second-playmaker pull-back', 'Support', 'ruck',
    '9 passes to you standing 5m behind the pod as the second option',
    'Set depth as the pod sets, receive standing still then attack',
    'cruise',
    'Give a second distributor behind the forwards so the ball can go tight or wide late.',
    'If 10 is that option, become the pod carrier instead.',
    'A blitz that targets the pull-back man; counter by taking the ball flat and carrying.',
    [[-6, 3], [-4, 4], [-2, 5], [0, 5.5]]],
  ['Offload support arc', 'Support', 'tackle contact',
    'A carrier in front of you is in a one-on-one tackle',
    'Accelerate onto his free-arm shoulder as contact happens',
    'max',
    'Take the offload and turn a tackle into a linebreak.',
    'If 7 is in the window, take the wider line and keep the width.',
    'A double tackle that pins both arms; counter by supporting from deeper for the pop.',
    [[-6, 5], [-3, 7], [0, 9], [3, 11]]],
  ['Maul-base break', 'Unders', 'maul',
    'The maul stalls or is about to be turned',
    'Take the ball out on the first sign of stall',
    'cruise',
    'Punch through the seam beside the maul before their guard re-sets.',
    'If 9 has taken the ball out, be his immediate carry option.',
    'A maul guard that never commits; counter by spinning the ball wide instead.',
    [[-1, 1], [0.3, 0], [1.6, -1.2], [3, -2.5]]],
  ['Base option — pick and go', 'Pillar', 'ruck',
    'The ruck is live and 9 is at the base',
    'Set a stride behind the hindmost foot, the side 9 is not; go on the ball',
    'cruise',
    'The pick-and-go option: a metre off the axis on the blind of 9, 0.3 m behind our safe line, planted; pick if the guard is soft, link with 9 if not.',
    'If the base is manned, be the near-pod carrier.',
    'A guard who sits on the pick; counter by popping to 9 for the wrap.',
    [[-2.6, -1.0], [-2.0, -1.0], [-0.6, -0.6], [1.0, -0.4]]],
  ['Link on the 9\'s hip', 'Support', 'ruck',
    '9 is carrying in open play',
    'Immediately; a carrying 9 always has the 8 on his hip (engine/forwardPack.ts EIGHT_LINK)',
    'sprint',
    'On the 9\'s blind hip, 1.4 m across and 1.3 m behind: the pick option, the offload target, the link with the forwards.',
    'If a back is on the hip, trail inside.',
    'A defender who shoots the 9; counter by taking the inside ball early.',
    [[-4, -1.4], [-2.6, -1.4], [-1.3, -1.4], [0.4, -1.2]]],
  ['Pick from the scrum base', 'Pillar', 'scrum base',
    'Our feed is won and their line is close (or the one-in-five call)',
    'The instant the ball is at your feet (engine/forwardPack.ts eightPicksFromScrum)',
    'sprint',
    'Pick and go from the base at their 9/8 channel instead of releasing to 9; the hand-off is a pick-up where you already stand.',
    'If 9 calls it, release clean and follow him.',
    'Their 8 and 7 sitting on the pick; counter by releasing to 9 and running the wrap.',
    [[-1.9, 0], [-1.0, 0.3], [0.5, 0.6], [2.5, 0.8]]],
]);
const d8 = mkLines(8, 'defence', [
  ['Fringe sweeper drop', 'Backfield', 'ruck',
    'They set up with a kicking 9 or a deep 10',
    'Drop as the ruck forms, hold 10-12m behind the line',
    'jog',
    'Cover the box kick, the chip and the inside break in one body.',
    'If 9 is sweeping, take the guard slot in the line instead.',
    'A team that never kicks; counter by pushing the sweeper into the line.',
    [[-1, 2], [-5, 3], [-9, 4], [-12, 5]]],
  ['Counter-ruck drive', 'Cleanout', 'tackle contact',
    'The carrier is held up or the ball is slow',
    'Arrive square, low, with a second body, and drive through the ball',
    'max',
    'Turn a slow ruck into a turnover or a penalty by shifting the whole breakdown.',
    'If a jackal is already on the ball, seal and support him instead.',
    'Attackers who present long and quickly; counter by attacking the carrier, not the ball.',
    [[-3, -1], [-1.5, -0.4], [-0.2, 0], [1, 0.4]]],
  ['Last-line cover arc', 'Scramble', 'ruck',
    'A break through the middle of the field',
    'Turn and run the deepest cover arc infield of the ball',
    'max',
    'Be the brake that delays the carrier long enough for the line to re-form.',
    'If 15 has the tackle, take the trailing support runner.',
    'An early pass to the support runner; counter by taking the support man yourself.',
    [[-4, 4], [-2, 10], [0, 16], [2, 21]]],
  ['Fold open to the second guard', 'Fold', 'ruck',
    'Their ruck is formed and you are not in it',
    'Round the box if you are in front of it; plant on the line 2.4 m outside the open edge',
    'sprint',
    'The second guard on the open side of the hindmost-foot line: the pick, the snipe and the first pod carry are all yours.',
    'If the guards are filled, sweep behind the line.',
    'A wide play that empties the middle; counter by folding with the ball, never sprinting ahead of it.',
    [[-1.0, 3.6], [2.4, 3.6], [3.0, 4.0], [3.0, 4.0]]],
]);

// ===== 9 SCRUM-HALF =====
const a9 = mkLines(9, 'attack', [
  ['Ruck-edge snipe', 'Unders', 'ruck',
    'The pillar stands up, turns his hips, or is more than 1.5m from the ruck',
    'Go on your own first touch of the ball; no wind-up',
    'max',
    'Punch through the seam beside the ruck — the single highest-percentage attacking gap.',
    'If a forward is already picking, become his latch or link.',
    'A pillar who stays low and square; counter by passing and going again next phase.',
    [[-1.5, 0], [-0.3, -0.4], [0.9, -0.8], [2.2, -1]]],
  ['Box-kick pocket step', 'Support', 'ruck',
    'Exit call is made inside your own 22',
    'Two steps back and across into the pocket as the ruck forms',
    'jog',
    'Create the kicking pocket behind the protection wall and get the hang time away.',
    'If protection is not set, delay one beat and re-call rather than kicking blind.',
    'A charge-down runner around the corner; counter by shortening the step and kicking earlier.',
    [[0, 0], [-1.5, -1], [-2.8, -1.6]]],
  ['Follow-the-ball link arc', 'Support', 'ruck',
    'The ball is passed away from the ruck',
    'Depart the moment the ball leaves your hands',
    'sprint',
    'Be at the base of the next breakdown within 2 seconds to keep tempo.',
    'If a forward is at the base, take the first-receiver slot instead.',
    'Slow ruck speed; counter by holding the ball and re-shaping rather than forcing it.',
    [[0, 0], [-1, 5], [-1.5, 10], [-1, 15]]],
  ['Wrap-around off the pick', 'Switch', 'ruck',
    'A forward picks and you loop behind him',
    'Loop behind him as he takes contact, hands ready',
    'sprint',
    'Get outside the fringe defence with the ball while they are focused on the carrier.',
    'If 10 is looping, run the decoy line and hold the pillar.',
    'A pillar who ignores the carrier; counter by giving the carrier the ball for real.',
    [[-1, 0.5], [-1.5, 2.5], [0, 4], [2, 5]]],
  ['Tempo tap arrowhead', 'Straight', 'ruck',
    'A penalty is awarded and their line is more than 5m back',
    'Tap the instant the referee signals, no glance around',
    'max',
    'Attack before their 10m retreat completes, when the defence is unstructured.',
    'If a forward is closer to the mark, hand it to him and become the link.',
    'A defence that retreats instantly and gets set; counter by not tapping and setting a phase.',
    [[0, 0], [1.5, 0.5], [3, 1], [4.5, 1.5]]],
]);
const d9 = mkLines(9, 'defence', [
  ['Shadow the opposing 9', 'Pillar', 'ruck',
    'They form a ruck and their 9 arrives at the base',
    'Mirror him around the ruck; never commit past the ball',
    'jog',
    'Deny the snipe and pressure the pass or the box kick without going offside.',
    'If 7 has the 9, take the pillar on the other side of the ruck.',
    'A 9 who passes early and runs a support line; counter by folding with him.',
    [[-0.5, -1], [-0.5, 0], [-0.5, 1], [-0.5, 2]]],
  ['Shallow sweep behind the line', 'Backfield', 'ruck',
    'Their shape suggests a box kick or a chip',
    'Drop as the ball is played, sit 12-15m behind the front line',
    'jog',
    'Field the short kick and cover the inside break while staying available to fold.',
    'If 15 is shallow, push up into the line as an extra pillar.',
    'A long kick over your head; counter by rotating deeper with 15.',
    [[-2, 1], [-6, 2], [-10, 3], [-13, 4]]],
  ['Fold-and-organise run', 'Fold', 'ruck',
    'The ball is moved to a new ruck',
    'Arrive with the ball, talking before you arrive',
    'sprint',
    'Re-set the pillar count and call the defensive numbers on both sides of the ruck.',
    'If the pillars are already set, drop into the sweep instead.',
    'A tempo attack that beats your voice; counter by pre-calling the next two phases.',
    [[-1, 0], [-1.5, 5], [-1, 10], [-0.5, 14]]],
]);

const LINES_F2: RunLine[] = [...a6, ...d6, ...a7, ...d7, ...a8, ...d8, ...a9, ...d9];
export default LINES_F2;
