import { mkLines, RunLine } from './lines';

// ===== 10 FLY-HALF =====
const a10 = mkLines(10, 'attack', [
  ['Flat first-receiver line', 'Straight', 'ruck',
    'You are first receiver and the defence is passive or drifting',
    'Take the ball moving forwards, as flat as you dare, at 8-10m depth',
    'cruise',
    'Hold the defender in front of you so the pass outside arrives against a static man.',
    'If 12 is first receiver, take the out-the-back depth behind him.',
    'A blitz defence; counter by playing early or kicking behind the rush.',
    [[-10, 6], [-8, 8], [-6, 10], [-4.5, 11.5]]],
  ['Out-the-back screen delivery', 'Decoy', 'ruck',
    'A pod or 12 runs a hard line across your face',
    'Hold your depth, pass behind the screen at the last moment',
    'jog',
    'Use the runner to fix two defenders and deliver the ball into the space they vacate.',
    'If 12 is the distributor, become the screen runner yourself.',
    'A defender who ignores the screen and pushes out; counter by giving the screen the ball.',
    [[-11, 6], [-10, 8], [-9, 10.5], [-8.5, 13]]],
  ['Wrap-around loop', 'Switch', 'ruck',
    'You pass to 12 and their defence bites in',
    'Pass, then loop immediately around the outside at pace',
    'sprint',
    'Add an extra body outside the ball and create a 3v2 on the edge.',
    'If 15 is already the extra man, hold your depth and become the kick option.',
    'A defence that tracks the looper; counter by faking the loop and going back inside.',
    [[-10, 7], [-8, 11], [-6, 15], [-4, 19]]],
  ['Kick-pass launch step', 'Straight', 'ruck',
    'Their winger has come off his wing or is pressing in the line',
    'Two steps across the field to open the hips, strike on the third',
    'jog',
    'Deliver a flat cross kick into the vacated 15m channel for the far winger.',
    'If 15 is the designated kicker on this play, run the decoy line outside.',
    'A winger who stays home; counter by playing the ball through the hands instead.',
    [[-10, 6], [-9, 8.5], [-8.5, 11]]],
  ['Chip and regather step-in', 'Unders', 'ruck',
    'A blitz defence is coming and their backfield is one man',
    'Take one step forward to commit the rush, then chip over the top',
    'cruise',
    'Beat the line speed by putting the ball behind it into the space they have vacated.',
    'If 15 has called the counter, pass and let him run it.',
    'A two-man backfield; counter by kicking long instead of short.',
    [[-10, 6], [-8.5, 6.5], [-7.5, 7]]],
]);
const d10 = mkLines(10, 'defence', [
  ['Channel-2 up-and-in', 'Blitz', 'ruck',
    'Their first receiver takes the ball in front of you',
    'Move on the pass, angle in slightly to shut the inside ball',
    'cruise',
    'Deny their 10 time, and take away the tip-on to the runner inside him.',
    'If a back-rower is defending your channel, drop into the second sweep.',
    'A pull-back pass; counter by keeping the outside defender flat as a lid.',
    [[-2, 8], [-0.8, 7.5], [0.4, 7], [1.4, 6.5]]],
  ['Drift with the ball', 'Drift', 'ruck',
    'They have an overlap outside you',
    'Move up and out together, passing threats outwards',
    'cruise',
    'Buy time for the line to slide and use the touchline as the extra defender.',
    'If 12 calls the blitz, ignore drift and go with him — the call must be unanimous.',
    'An unders line back inside the drift; counter by leaving one man square.',
    [[-2, 8], [-1, 11], [0, 14], [0.8, 17]]],
  ['Backfield drop-off', 'Backfield', 'ruck',
    'Their 9 or 10 sets up for a kick',
    'Turn and drop as the kicker shapes, before the ball is struck',
    'sprint',
    'Become the second man in the backfield so 15 is not alone against a kicking game.',
    'If 15 is already covering your side, stay in the line.',
    'A run-first attack that exploits your absence; counter by reading the kick cue properly.',
    [[-2, 8], [-8, 10], [-14, 12], [-19, 13]]],
]);

// ===== 11 LEFT WING =====
const a11 = mkLines(11, 'attack', [
  ['Outside-break finishing line', 'Overs', 'ruck',
    'You receive the ball in a 1v1 with space outside',
    'Take the ball at full pace, angle out then straighten',
    'max',
    'Get outside the last defender and finish, using the touchline only at the last moment.',
    'If 15 is outside you, straighten and give him the ball on the outside.',
    'A defender who drifts and shepherds you out; counter by stepping back inside.',
    [[-2, 18], [2, 22], [7, 25], [13, 27]]],
  ['Blindside extra-man arrival', 'Insertion', 'ruck',
    'The ball is on the far edge and the short side is under-manned',
    'Start the run as the ball leaves the previous ruck, arrive before the pass',
    'max',
    'Be the surprise extra body on the short side, where defences are chronically short.',
    'If 15 has filled the short side, hold as the far-side backfield cover.',
    'A blindside winger who mirrors your run; counter by swinging the ball back wide instead.',
    [[-4, -14], [-2, -20], [0, -26], [2, -31]]],
  ['Unders cut-back off 13', 'Unders', 'ruck',
    'Their defence is drifting hard and the inside is open',
    'Angle back inside as 13 receives the ball',
    'sprint',
    'Attack the space the drift has opened behind their pressing outside defender.',
    'If 12 is running the unders, hold your width and stay the finisher.',
    'A defender who stays square; counter by holding width and going outside instead.',
    [[-3, 20], [-1, 16], [1, 12], [3, 9]]],
  ['Kick-chase outside lane', 'Chase', 'kick landing',
    'A box kick or contestable is put up in your channel',
    'Leave with the kicker\'s foot, arrive as the ball lands',
    'max',
    'Contest in the air or tackle the catcher instantly to prevent the counter.',
    'If 14 is contesting, become the ground support and secure the loose ball.',
    'A quick catch-and-pass; counter by chasing the receiver, not the catcher.',
    [[-25, 2], [-16, 1], [-8, 0.5], [0, 0]]],
  ['Cross-kick attack jump', 'Insertion', 'kick landing',
    '10 shapes to cross kick and you are one-on-one in the corner',
    'Start the run late so you arrive under the ball at full speed',
    'max',
    'Win the ball above the defender and score, or tap it back to the support.',
    'If 15 is on the cross kick, block for him and take the tap-back.',
    'A defender who turns and runs early; counter by shortening the kick.',
    [[-8, -4], [-5, -2], [-2, -0.5], [0, 0]]],
]);
const d11 = mkLines(11, 'defence', [
  ['Edge drift and shepherd', 'Drift', 'ruck',
    'Their attack has numbers on your edge',
    'Move up and out with your inside man, never in front of him',
    'cruise',
    'Force the carrier towards the touchline and take away the outside break.',
    'If 15 is up outside you, tuck in one channel and defend the inside.',
    'A kick over your head into the corner; counter by leaving the fullback deep.',
    [[-2, -14], [-1, -18], [0, -22], [0.5, -26]]],
  ['Backfield third rotation', 'Backfield', 'ruck',
    'The ball moves across the field and the kicking threat shifts',
    'Slide continuously with the ball; never stand still',
    'jog',
    'Keep the field split into three covered thirds with 14 and 15 at all times.',
    'If 15 slides to your third, push up into the front line.',
    'A kick into the seam between thirds; counter by talking and closing the seam early.',
    [[-18, -20], [-16, -14], [-15, -8], [-15, -2]]],
  ['Corner-flag scramble', 'Scramble', 'ruck',
    'They break into the space behind you on your wing',
    'Turn and run the arc to a point on the touchline ahead of the carrier',
    'max',
    'Beat him to the corner and force him into touch rather than tackling from behind.',
    'If 15 has the covering angle, take the inside support runner instead.',
    'An inside pass before the corner; counter by taking the support runner.',
    [[-8, -18], [-2, -24], [4, -29], [10, -32]]],
]);

// ===== 12 INSIDE CENTRE =====
const a12 = mkLines(12, 'attack', [
  ['Flat crash unders', 'Unders', 'ruck',
    '10 has the ball and their 12 is drifting outwards',
    'Angle back inside off 10\'s shoulder, take the ball flat',
    'sprint',
    'Break the drift by attacking the inside shoulder and getting over the gain line.',
    'If a forward is running the unders, take the straight line outside 10 instead.',
    'A defender who stays square; counter by tipping the ball on outside.',
    [[-9, 12], [-6, 11], [-3, 10.5], [0, 10.5], [2, 11]]],
  ['Tip-on to the outside runner', 'Straight', 'ruck',
    'You receive flat with their 12 committed to you',
    'Draw him fully, then pass off one hand at contact distance',
    'cruise',
    'Turn a 2v2 into a linebreak by removing the defender in front of 13.',
    'If 10 is the distributor, become the runner off his shoulder.',
    'A defender who hovers between you; counter by carrying instead of passing.',
    [[-8, 12], [-5.5, 13], [-3, 14], [-1, 15]]],
  ['Switch with 10', 'Switch', 'ruck',
    'Their line speed is high and a change of angle is needed',
    'Cross behind 10 as he steps towards the touchline',
    'sprint',
    'Turn the rushing defenders inwards and attack the space they have overrun.',
    'If 13 is switching, run the block line to hold the inside defender.',
    'A defence with a passive lid; counter by playing wide and using width.',
    [[-9, 14], [-8, 11], [-6, 8], [-4, 6]]],
  ['Second-phase pull-back', 'Support', 'ruck',
    'A pod carries and the defence has folded flat and narrow',
    'Stand 12m back and take the pull-back pass moving forwards',
    'cruise',
    'Give a deep distributor who can attack either edge from behind the forwards.',
    'If 10 is the pull-back, run the front-door line to hold defenders.',
    'A defence that leaves a spy on the pull-back; counter by going short instead.',
    [[-12, 8], [-10, 10], [-8, 12], [-6, 13.5]]],
  ['Trailing support off 13', 'Support', 'tackle contact',
    '13 breaks the line outside you',
    'Chase the inside shoulder immediately; never stop running',
    'max',
    'Take the inside offload and turn a half-break into a try.',
    'If 10 is in the window, take the outside line and stay wide.',
    'A tackler who pins the ball arm; counter by supporting deeper for the pop.',
    [[-6, 14], [-2, 18], [2, 22], [6, 26]]],
]);
const d12 = mkLines(12, 'defence', [
  ['Midfield blitz with 13', 'Blitz', 'ruck',
    'Their 12 receives the ball in your channel',
    'Go on the pass, connected with 13, targeting the outside shoulder',
    'sprint',
    'Dominate the midfield collision and force the ball backwards or to the floor.',
    'If 13 calls drift, drift — the midfield pair must always match calls.',
    'A short unders runner inside you; counter by keeping the guard flat.',
    [[-2, 12], [-0.5, 12.5], [1, 13], [2.5, 13.5]]],
  ['Inside-shoulder hold', 'Drift', 'ruck',
    'Your outside man shoots out of the line',
    'Hold and slide slightly out, never following him up',
    'jog',
    'Cover the seam his shoot has created so the unders line has no gap.',
    'If 10 is already holding the seam, push out and take the next man.',
    'An out-the-back play that ignores the seam; counter by re-connecting immediately.',
    [[-2, 12], [-1.5, 14], [-1, 16]]],
  ['Cut-back cover line', 'Scramble', 'ruck',
    'A break happens outside you and the carrier looks to come back inside',
    'Turn and run infield of the ball, never behind it',
    'max',
    'Own the cut-back lane, which is where most broken-field tries are scored.',
    'If 9 or 8 has the cut-back covered, take the outside support runner.',
    'A wide-wide continuation; counter by trusting the edge and holding the inside.',
    [[-4, 14], [-6, 9], [-8, 4], [-9, -1]]],
]);

// ===== 13 OUTSIDE CENTRE =====
const a13 = mkLines(13, 'attack', [
  ['Straight-and-late overs', 'Overs', 'ruck',
    'You get the ball with the winger outside you and a defender drifting',
    'Run straight first, then angle out only in the last 5m',
    'max',
    'Hold their 13 in place so the winger receives against a static outside defender.',
    'If 15 has inserted outside you, straighten and give him the ball early.',
    'A hard blitz from their 13; counter by playing the ball earlier and flatter.',
    [[-6, 18], [-3, 19], [0, 20.5], [3, 22.5]]],
  ['Seam attack off the tip-on', 'Unders', 'ruck',
    '12 fixes their 12 and tips the ball on to you',
    'Take the ball at pace on the angle into the 13-14 seam',
    'max',
    'Attack the seam between their 13 and winger, the softest gap in most defences.',
    'If 15 is running the seam, run the decoy line and hold their 13.',
    'A winger who jams in; counter by passing early to your own winger.',
    [[-6, 20], [-3, 21], [0, 22], [3, 23]]],
  ['Draw-and-pass to the corner', 'Straight', 'ruck',
    'You break the line and the fullback comes across',
    'Fix the fullback with your eyes and hips, pass one stride before contact',
    'max',
    'Commit the last defender and put the winger in untouched.',
    'If the winger is covered, hold the ball and take the tackle to set the ruck.',
    'A fullback who never commits; counter by running past him instead of passing.',
    [[-2, 22], [3, 25], [8, 28], [12, 31]]],
  ['Late switch back inside', 'Switch', 'ruck',
    'Their defence has drifted hard and the inside is empty',
    'Take the ball then cut back sharply off your outside foot',
    'max',
    'Punish an over-drifting defence by attacking the space they have vacated.',
    'If 12 is running the cut-back, hold your width as the finisher.',
    'A defender who stays square; counter by continuing straight and going outside.',
    [[-4, 20], [-1, 19], [2, 16], [5, 12]]],
  ['Kick-chase reclaim arc', 'Chase', 'kick landing',
    '10 puts a grubber or chip in behind their line',
    'Leave with the kick, run the arc to arrive as the ball bounces up',
    'max',
    'Regather in behind or force the error in their own 22.',
    'If the winger is on the chase, take the inside line for the loose ball.',
    'A fullback who covers early; counter by kicking flatter and shorter.',
    [[-18, 6], [-12, 8], [-6, 10], [0, 11]]],
]);
const d13 = mkLines(13, 'defence', [
  ['Outside anchor drift', 'Drift', 'ruck',
    'They have the ball wide with numbers',
    'Move up and out with the line, never letting a man get outside you',
    'cruise',
    'Set the edge of the defence and push the attack towards the touchline.',
    'If 12 calls blitz, blitz — the midfield pair must be unanimous.',
    'A cut-back inside the drift; counter by leaving the 12 square as the lid.',
    [[-2, 18], [-1, 22], [0, 26], [0.5, 30]]],
  ['Jam on the tip-on man', 'Blitz', 'ruck',
    'Their 12 is a distributor and their 13 is the strike runner',
    'Shoot on the tip-on, targeting the receiver, not the passer',
    'max',
    'Kill the strike runner behind the gain line and turn their shape backwards.',
    'If your winger is jamming, hold and cover the inside instead.',
    'A pull-back behind your jam; counter by only jamming on a confirmed cue.',
    [[-2, 18], [0, 18.5], [2, 19], [4, 19.5]]],
  ['Touchline funnel shepherd', 'Shepherd', 'ruck',
    'Their winger gets the ball outside you with space',
    'Run the curve that closes the outside first',
    'max',
    'Force him into the touchline so it becomes the extra defender.',
    'If your winger has him covered, take the inside support runner.',
    'A step back inside; counter by keeping the inside foot planted.',
    [[-2, 20], [2, 25], [6, 29], [9, 32]]],
]);

// ===== 14 RIGHT WING =====
const a14 = mkLines(14, 'attack', [
  ['Touchline finish', 'Overs', 'ruck',
    'You receive with the touchline as your only constraint',
    'Take it at full pace; use the outside foot only in the last 5m',
    'max',
    'Beat the last defender on the outside and finish in the corner.',
    'If 15 is outside you, straighten and pass instead.',
    'A cover defender arriving on the angle; counter by stepping back inside early.',
    [[-2, 18], [2, 22], [7, 25], [13, 27]]],
  ['Aerial contest chase', 'Chase', 'kick landing',
    'A contestable kick goes up in your 15m channel',
    'Leave with the kicker\'s foot; time the last three strides to jump',
    'max',
    'Win the ball in the air or knock it back into our chasers.',
    'If 15 is contesting, become the ground support and secure the ball.',
    'A catcher who takes it cleanly and passes; counter by tackling in the air-safe zone after landing.',
    [[-28, -3], [-19, -2], [-9, -1], [0, 0]]],
  ['Inside cut off the fullback', 'Unders', 'ruck',
    'Their winger has jammed in and the space is inside him',
    'Cut back inside as 13 receives, at pace',
    'max',
    'Attack the space their jamming winger has left open.',
    'If 15 has that line, hold width and stay the finisher.',
    'A winger who holds his width; counter by going outside instead.',
    [[-3, 22], [-1, 18], [1, 14], [3, 11]]],
  ['Blindside arrival extra man', 'Insertion', 'ruck',
    'Play has been on the far edge and the ball is coming back',
    'Start the cross-field run one phase early',
    'max',
    'Arrive as the unexpected extra man on the under-manned side.',
    'If 11 is arriving on that side, hold the far backfield instead.',
    'A defence that counts numbers; counter by disguising the arrival behind forwards.',
    [[-4, 16], [-2, 8], [0, 0], [2, -8]]],
  ['Support arc off the break', 'Support', 'tackle contact',
    '13 or 15 breaks the line inside you',
    'Accelerate onto the outside shoulder and stay in the pass window',
    'max',
    'Take the final pass and finish, or offer the outside option to draw the cover.',
    'If 15 has the outside line, come back inside for the short ball.',
    'A cover defender who takes you and lets the carrier run; counter by staying square.',
    [[-4, 20], [1, 24], [6, 27], [11, 30]]],
]);
const d14 = mkLines(14, 'defence', [
  ['Edge drift and touchline squeeze', 'Drift', 'ruck',
    'They attack your edge with numbers',
    'Move up and out with your inside man',
    'cruise',
    'Compress the space between the ball and the touchline until there is no room.',
    'If 15 is up outside you, tuck in one channel.',
    'A cross kick behind you; counter by leaving 15 deep on your side.',
    [[-2, 18], [-1, 22], [0, 26], [0.5, 30]]],
  ['Backfield third rotation', 'Backfield', 'ruck',
    'The ball crosses the field and the kicking threat shifts',
    'Slide continuously with the ball',
    'jog',
    'Keep the three covered thirds intact with 11 and 15.',
    'If 15 covers your third, push up into the front line.',
    'A kick into the seam between thirds; counter by talking and closing early.',
    [[-18, 22], [-16, 16], [-15, 10], [-15, 4]]],
  ['Kick-return contest jump', 'Backfield', 'kick landing',
    'A high ball is put into your backfield third',
    'Call "mine" early, get under it, jump with the knee up',
    'sprint',
    'Take the ball cleanly and either counter or clear before the chase arrives.',
    'If 15 calls it, block for him and become the first support.',
    'An aggressive chaser contesting; counter by taking it two-handed in front of the face.',
    [[-10, 5], [-6, 3], [-3, 1.5], [0, 0]]],
]);

// ===== 15 FULLBACK =====
const a15 = mkLines(15, 'attack', [
  ['Late insertion outside 13', 'Insertion', 'ruck',
    '10 calls "in" and their line has folded flat with no spare man',
    'Start deep and time the run so you arrive at full pace as the pass is thrown',
    'max',
    'Create the extra man exactly where they have no defender.',
    'If 14 has that slot, insert inside 13 and become the link.',
    'A defence that counts and slides; counter by inserting on the other side.',
    [[-14, 12], [-9, 16], [-4, 20], [0, 24]]],
  ['Blindside insertion', 'Insertion', 'ruck',
    'The short side is under-defended after a wide ruck',
    'Start the run before the 9 turns his head',
    'max',
    'Attack the short side where the defence has folded to the open side.',
    'If 11 has arrived on the blind, take the openside insertion instead.',
    'A winger who holds the blind; counter by using the run as a decoy.',
    [[-14, 4], [-10, -2], [-6, -8], [-2, -13]]],
  ['Counter-attack seam run', 'Overs', 'catch point',
    'You catch a kick with the chase line unstructured',
    'Attack the seam between two chasers immediately; do not run sideways',
    'max',
    'Turn defence into attack by breaking the first chase line before it connects.',
    'If a winger has called the counter, become the pull-back link behind him.',
    'A connected, disciplined chase; counter by re-kicking long instead.',
    [[0, 0], [5, 3], [11, 6], [17, 8]]],
  ['Pull-back link behind the line', 'Support', 'catch point',
    'A winger catches and counters and you are behind him',
    'Stay 8-10m behind and infield, moving forwards',
    'sprint',
    'Give the catcher a safe backwards option to change the point of attack.',
    'If 10 is the pull-back, sprint wide and become the finisher.',
    'A chaser who reads the pull-back; counter by taking the ball flat instead.',
    [[-9, -6], [-6, -2], [-3, 2], [0, 6]]],
  ['Re-kick step and strike', 'Straight', 'catch point',
    'You catch the ball with a set chase in front of you',
    'One step infield to open the angle, strike on the second',
    'jog',
    'Turn the ball around into the space behind their chase and win the territory battle.',
    'If pressure has arrived, kick straight to touch and re-set.',
    'A charge-down chaser; counter by taking a step back before striking.',
    [[0, 0], [-1.5, 3], [-2.5, 6]]],
]);
const d15 = mkLines(15, 'defence', [
  ['Deep-third slide', 'Backfield', 'ruck',
    'The ball moves across the field in their possession',
    'Slide continuously, staying central to the two most likely kick zones',
    'jog',
    'Never be square to the ball; always be a step ahead of the kick.',
    'If a winger is deeper than you, come up as the second-last defender.',
    'A kick into the vacated third; counter by rotating the whole triangle, not just yourself.',
    [[-24, -10], [-24, -2], [-24, 6], [-24, 14]]],
  ['Last-line one-on-one', 'Shepherd', 'ruck',
    'A carrier is through the line and only you are left',
    'Slow down, shorten your steps, close the outside first',
    'cruise',
    'Delay the carrier and force him inside towards the arriving cover.',
    'If a covering player has the angle, drop and cover the support runner instead.',
    'A well-timed offload; counter by taking the support man and letting cover take the carrier.',
    [[-20, 12], [-14, 15], [-8, 17], [-3, 18]]],
  ['Front-line insertion (defensive)', 'Blitz', 'ruck',
    'They are short of numbers and we can gamble one extra defender',
    'Insert outside 13 as the pass is made, connected with the winger',
    'sprint',
    'Create a defensive overlap and force an error on their edge.',
    'If a winger is already up, stay deep and cover the kick — never both.',
    'A chip over the top into your vacated space; counter by only inserting inside their 22.',
    [[-20, 18], [-13, 20], [-7, 22], [-2, 24]]],
]);

const LINES_BACKS: RunLine[] = [
  ...a10, ...d10, ...a11, ...d11, ...a12, ...d12, ...a13, ...d13, ...a14, ...d14, ...a15, ...d15,
];
export default LINES_BACKS;
