import { mkLines, RunLine } from './lines';

// ===== 1 LOOSEHEAD PROP =====
const a1 = mkLines(1, 'attack', [
  ['Tight pod straight carry', 'Straight', 'ruck',
    'Scrum-half looks at the near pod and calls "1 up"',
    'Leave on the 9\'s hands touching the ball; arrive at the ball 1m before the gain line',
    'cruise',
    'Win the collision square so the ruck forms in front of the gain line and the next pass is off front-foot ball.',
    'If another prop is already the pod carrier, become the left-hip latch instead.',
    'A dominant double tackle with a chop-and-choke; the counter to that is to shorten the pass and carry lower.',
    [[-4, 4], [-2, 4.5], [0, 5], [2, 5.2]]],
  ['Latch and drive', 'Maul, ruck', 'ruck',
    'A team-mate in your pod is called as the carrier',
    'Bind before contact, never after; you must be attached as he takes the pass',
    'cruise',
    'Add a second body to the collision so the carrier gets an extra 2m and the ball stays off the deck.',
    'If two latches are already attached, peel off and become the first cleaner instead.',
    'Defenders splitting the latch by attacking the seam between the two bodies.',
    [[-4, 6], [-2, 5.6], [0, 5.2], [1.5, 5]]],
  ['Cleanout gate arc', 'Cleanout', 'tackle contact',
    'Your pod team-mate is tackled',
    'Depart the instant contact is made; target arrival within 1.2 seconds',
    'sprint',
    'Arrive through the gate at the jackal\'s near shoulder, low, and lift him off the ball.',
    'If a team-mate is already over the ball securing it, take the far post and stay on your feet.',
    'A jackal who is already square and loaded; counter by hitting his hip, not his back.',
    [[-3, -3], [-1.5, -1], [-0.4, 0], [0.6, 0.6]]],
  ['Short-side pick angle', 'Unders', 'ruck',
    '9 scans blind and the guard has folded open',
    'Set your feet as the ball arrives at the base; go on the 9\'s first step',
    'cruise',
    'Attack the inside shoulder of the pillar in the 2m channel next to the ruck.',
    'If 3 or 2 has the pick, latch and drive him through the pillar.',
    'A disciplined pillar who stays low and square; counter by going one more phase before picking.',
    [[-2, -1], [-0.8, -1.6], [0.4, -2.2], [1.6, -3]]],
  ['Reload fold to next pod', 'Fold', 'ruck',
    'You have been cleaned out or presented the ball',
    'Rise within 3 seconds and fold behind the ruck, never in front of it',
    'jog',
    'Rebuild the 1-3-3-1 so the far pod has three bodies for the next phase.',
    'If the next pod is already three strong, keep folding to the far edge as the +1.',
    'Defences that fold faster than you reload; counter with faster ruck speed, not faster running.',
    [[0.5, 0.5], [-2, 3], [-3.5, 7], [-4, 12]]],
]);
const d1 = mkLines(1, 'defence', [
  ['Pillar shuffle', 'Pillar', 'ruck',
    'The opposition set a ruck within 5m of you',
    'Feet set before the ball is available; never move forwards past the ball',
    'hold',
    'Deny the 9 snipe and the one-out pick by owning the 1m channel next to the ruck.',
    'If a team-mate is on the pillar, become the post one metre outside him.',
    'A snipe from the far side of the ruck; counter by shuffling with the 9\'s eyes, not his feet.',
    [[-0.5, -1.2], [-0.5, -0.6], [-0.5, 0], [-0.5, 0.6]]],
  ['Chop tackle step-up', 'Blitz', 'ruck',
    'A tight carrier takes the ball one pass from the ruck',
    'One step forward only, on the pass leaving the 9\'s hands',
    'cruise',
    'Meet the carrier on or in front of the gain line and cut the legs so the leg-drive dies.',
    'If your inside man has already committed, hold and take the ball carrier\'s inside shoulder.',
    'A latched carrier; counter by tackling the ball-carrying hip, not the latch.',
    [[-1.5, 3], [-0.6, 3.2], [0.2, 3.4]]],
  ['Defensive fold arc', 'Fold', 'ruck',
    'The ball is played away from your side of the ruck',
    'Depart as the pass is made; run behind the offside line at all times',
    'sprint',
    'Arrive on the inside of the ball as the new pillar, so the line never dog-legs.',
    'If two forwards fold with you, the second stays as sweeper behind the pillars.',
    'Quick-tempo attacks that beat the fold; counter by pre-folding one man on the 9\'s look.',
    [[-1, 0], [-2.5, 5], [-2.5, 10], [-1.5, 14]]],
]);

// ===== 2 HOOKER =====
const a2 = mkLines(2, 'attack', [
  ['Middle pod tip-on line', 'Straight', 'ruck',
    '9 passes to the three-man pod and you are the middle man',
    'Arrive flat, hands up, one stride before the ball',
    'cruise',
    'Take the ball square and either carry or tip on to the runner behind, holding two defenders.',
    'If another forward is the tip-on hub, run the hard decoy off his shoulder.',
    'A blitzing guard who takes the tip-on man; counter by carrying yourself instead of passing.',
    [[-3.5, 5], [-1.7, 5.5], [0, 6], [1.5, 6.3]]],
  ['Front peel off the maul', 'Unders', 'maul',
    'The maul is halted or the call is "peel"',
    'Break as the maul stops moving, not before',
    'cruise',
    'Attack the seam between the maul and the touchline where their guard has folded in.',
    'If 6 has peeled already, latch him and drive.',
    'A defender left as the maul guard; counter by peeling on the second stall, not the first.',
    [[-2, -2], [-0.5, -3], [1, -4.5], [2.5, -6]]],
  ['Goal-line pick unders', 'Unders', 'ruck',
    'Red-zone phase, the post defender has stood up tall',
    'Go on the 9\'s hands, low body height from the first step',
    'cruise',
    'Get under the post defender\'s chest and reach the ball over the line.',
    'If 8 is picking, become his latch and drive the legs.',
    'A double tackle with a hold-up; counter by twisting and placing backwards.',
    [[-1.5, 1.5], [-0.5, 1], [0.5, 0.8], [1.5, 0.8]]],
  ['Cleanout gate arc', 'Cleanout', 'tackle contact',
    'A team-mate is tackled within 10m of you',
    'Leave on contact; arrive within 1.2 seconds',
    'sprint',
    'Clear the threat at the near shoulder and stay on your feet to be available next phase.',
    'If the ball is already secure, do not enter — stand up as the next pillar.',
    'Defences that send only one jackal and keep numbers in the line; counter by not over-committing.',
    [[-3, -2.5], [-1.5, -1], [-0.3, 0], [0.7, 0.5]]],
  ['Lineout maul spine drive', 'Maul', 'maul',
    'The jumper lands and transfers the ball to you',
    'Bind on the landing, before their defenders arrive',
    'cruise',
    'Hold the ball at the back and steer the drive towards the posts.',
    'If 8 is holding the ball at the back, bind as the second-row engine.',
    'A defence that sacks the jumper on landing; counter by lowering and shortening the transfer.',
    [[-1, 0], [0.5, 1], [2, 2.5], [3.5, 4]]],
]);
const d2 = mkLines(2, 'defence', [
  ['Post defender hold', 'Pillar', 'ruck',
    'Ruck formed, you are one man out from the pillar',
    'Hold until the ball is passed past you; then move',
    'hold',
    'Own the second channel so the pick-and-go and the short pop have no space.',
    'If the post is taken, become the guard one further out.',
    'A tip-on pass in front of you; counter by tackling the receiver, not the passer.',
    [[-0.8, 2], [-0.8, 2.6], [-0.8, 3.2]]],
  ['Line-speed connect', 'Blitz', 'ruck',
    'Their 9 passes to a first receiver',
    'Move on the ball leaving the 9\'s hands, shoulder-linked with the men either side',
    'cruise',
    'Compress their time and space while keeping the line flat — no individual shooting.',
    'If your inside man shoots out of the line, hold and cover his inside shoulder.',
    'A pull-back pass behind the rushing line; counter by keeping one man passive as a lid.',
    [[-2, 5], [-0.8, 5.4], [0.4, 5.8], [1.5, 6.2]]],
  ['Jackal support seal', 'Jackal', 'tackle contact',
    'Your 7 gets over the ball',
    'Arrive within one second of the tackle, from behind',
    'sprint',
    'Shield the jackal from the cleanout so he wins the penalty.',
    'If two sealers are there, get back into the defensive line instead.',
    'A double cleanout that goes through both bodies; counter by seal-blocking lower.',
    [[-3, -2], [-1.5, -0.8], [-0.4, 0]]],
]);

// ===== 3 TIGHTHEAD PROP =====
const a3 = mkLines(3, 'attack', [
  ['Outside-shoulder pod carry', 'Overs', 'ruck',
    'You are the outside man of the near pod',
    'Leave a beat later than the middle man so you arrive behind the ball',
    'cruise',
    'Attack the guard\'s outside shoulder to drag the defensive line outwards and open the inside.',
    'If the outside slot is taken, take the tail of the next pod.',
    'A drifting guard; counter by straightening and running unders instead.',
    [[-4, 7], [-2, 8], [0, 8.8], [1.8, 9.4]]],
  ['Blindside seal line', 'Unders', 'ruck',
    'The play has gone open and the short side is empty',
    'Set feet as the ruck forms; hold, do not follow the ball',
    'hold',
    'Occupy the short side so the 9 always has a legal option and the blind is never a free channel.',
    'If 1 already holds the short side, fold openside as the pod tail.',
    'Attacks that never use the short side; counter by folding open after two phases.',
    [[-2, -3], [-1.5, -4], [-1, -5]]],
  ['Cleanout far-post arc', 'Cleanout', 'tackle contact',
    'A team-mate is tackled and the near post is already filled',
    'Leave on contact and run past the near shoulder to the far one',
    'sprint',
    'Secure the far side of the ball so a counter-ruck cannot come around the corner.',
    'If both posts are filled, stand up as the next pillar and let the ball go.',
    'A counter-ruck that arrives with three; counter by having the second man square the ruck.',
    [[-3, 3], [-1.4, 1.5], [-0.2, 0.4], [0.8, -0.4]]],
  ['Maul right-side drive', 'Maul', 'maul',
    'The maul forms and you are the right-front bind',
    'Bind immediately on the jumper landing',
    'cruise',
    'Drive at 45° towards the posts, keeping the maul square and legal.',
    'If the front is full, bind into the second row and add weight low.',
    'A defence swimming around the front; counter by re-angling the drive infield.',
    [[-1, 1], [0.4, 2.2], [1.8, 3.6], [3.2, 5]]],
  ['Reload to the middle pod', 'Fold', 'ruck',
    'Phase ends and you are on the wrong side of the field',
    'Rise, fold behind the ruck, arrive within 5 seconds',
    'jog',
    'Rebalance the pod distribution so no third of the field is empty.',
    'If the middle pod is complete, continue to the far edge.',
    'Fast tempo that beats the reload; counter by holding a phase to re-shape.',
    [[0.5, -1], [-2, 0], [-4, 3], [-4.5, 8]]],
]);
const d3 = mkLines(3, 'defence', [
  ['Far-side pillar hold', 'Pillar', 'ruck',
    'Ruck formed and 1 has the near pillar',
    'Set before the ball is available; mirror the 9',
    'hold',
    'Guard the opposite side of the ruck so both edges of the breakdown are sealed.',
    'If the far pillar is filled, become the second post shoulder to shoulder.',
    'A snipe straight over the top of the ruck; counter by squeezing the two pillars together.',
    [[-0.5, 1.2], [-0.5, 0.6], [-0.5, 0]]],
  ['Short-side seal defence', 'Drift', 'ruck',
    'The attack sets up on the short side',
    'Move on the pass, sliding not rushing',
    'jog',
    'Compress the blind channel to touch so there is no room for their winger to run.',
    'If 6 has the blind, fold openside and defend the guard channel.',
    'A cross kick into the blind corner; counter by leaving the winger deep.',
    [[-1, -2], [-0.5, -4], [0, -6.5]]],
  ['Trail cover on the inside', 'Scramble', 'ruck',
    'The ball has gone wide and you cannot reach the edge',
    'Turn immediately, run the infield line',
    'sprint',
    'Cover the inside cut-back rather than chasing a game you cannot win on the outside.',
    'If a faster forward is already inside, drop behind him as the second cover.',
    'A wide-wide attack with no cut-back; counter by trusting the edge and folding early.',
    [[-1, 0], [-3, 5], [-4, 11], [-4, 17]]],
]);

// ===== 4 LOCK (blindside) =====
const a4 = mkLines(4, 'attack', [
  ['Pod lead carry, straight', 'Straight', 'ruck',
    'Called as the lead carrier of the three-man pod',
    'Set 6-8m back, leave on the 9 looking at you',
    'sprint',
    'Hit the line at maximum speed, square, and get past the gain line every time.',
    'If the pod already has a lead carrier, take the tail and run the trailing option.',
    'A choke tackle that holds you up; counter by getting lower and driving the legs.',
    [[-7, 5], [-4, 5.5], [-1, 6], [1.5, 6.3]]],
  ['Second-man unders off 10', 'Unders', 'ruck',
    '10 takes the ball flat and you are the runner behind him',
    'Time the run so you cross behind him as he receives',
    'sprint',
    'Attack the inside shoulder of the drifting defender in the 10-12 seam.',
    'If 12 is running that line, take the wider overs line instead.',
    'A defender who sits in the seam; counter by using it as a decoy and going out the back.',
    [[-9, 8], [-6, 6.5], [-3, 5.5], [0, 5], [2, 5]]],
  ['Latch drive on the carrier', 'Maul', 'ruck',
    'A team-mate is the pod carrier',
    'Bind before contact and drive on the whistle of impact',
    'cruise',
    'Turn a one-man carry into a two-man drive to win an extra 2m and keep the ball alive.',
    'If two latches are attached, become the first cleaner.',
    'A defence that tackles the latch and lets the ball go; counter by peeling off late.',
    [[-6, 7], [-3.5, 6.3], [-1, 5.8], [0.8, 5.6]]],
  ['Lineout maul point drive', 'Maul', 'maul',
    'You catch the lineout ball at the middle',
    'Land facing the try line, transfer, then drive',
    'cruise',
    'Become the point of the maul and set the driving angle towards the posts.',
    'If 5 caught it, bind into the second row and add weight.',
    'A pre-emptive sack; counter by landing with the ball already behind you.',
    [[0, 0], [1.2, 1.4], [2.6, 3], [4, 4.6]]],
  ['Reload arc to far pod', 'Fold', 'ruck',
    'You have carried or cleaned and the ball is going away',
    'Rise and fold within 4 seconds',
    'jog',
    'Refill the far pod so the next phase has three forwards on the far side.',
    'If the far pod is complete, become the +1 next to the backline.',
    'Two-phase-quick attack; counter by leaving one forward pre-folded.',
    [[1, 6], [-2, 8], [-5, 12], [-6, 17]]],
]);
const d4 = mkLines(4, 'defence', [
  ['Guard step and square', 'Blitz', 'ruck',
    'You are the guard, two out from the pillar, and the ball is passed',
    'One-and-a-half steps forward, square shoulders',
    'cruise',
    'Dominate the tight carrier behind the gain line and stall the attack\'s momentum.',
    'If the guard slot is filled, move one channel wider and connect.',
    'A tip-on pass past you; counter by tackling the receiver, not the first man.',
    [[-2, 3.5], [-0.8, 3.8], [0.4, 4]]],
  ['Fold and re-set inside', 'Fold', 'ruck',
    'The ball moves two passes away from you',
    'Depart on the second pass, run behind the offside line',
    'sprint',
    'Arrive inside the ball so the defensive line stays connected with no dog-leg.',
    'If enough men have folded, stay as the sweeper behind the pillars.',
    'An attack that plays back to the vacated side; counter by leaving a two-man seal.',
    [[-1.5, 3], [-3, 8], [-3, 13], [-2, 17]]],
  ['Maul defence entry', 'Maul', 'maul',
    'They form a driving maul from a lineout',
    'Enter square at the ball-carrying side within one second of formation',
    'cruise',
    'Attack the maul\'s ball-side shoulder to split it or force the ball to the back early.',
    'If the maul is already engaged by two, join the back and drive to swing it.',
    'A well-bound, moving maul; counter by not engaging and defending the base instead.',
    [[-2, 1.5], [-0.8, 1], [0.2, 0.6]]],
]);

// ===== 5 LOCK (openside) =====
const a5 = mkLines(5, 'attack', [
  ['Far pod overs line', 'Overs', 'ruck',
    'You lead the far pod two passes from the ruck',
    'Leave as the first pass is thrown so you arrive on the second',
    'sprint',
    'Attack outside the last forward defender to bend their line and create the edge.',
    'If the far pod has a lead carrier, become the +1 outside the backline.',
    'A drift defence that slides with you; counter by straightening late into the seam.',
    [[-8, 12], [-5, 13], [-2, 14], [1, 14.5]]],
  ['Screen runner behind 10', 'Decoy', 'ruck',
    '10 calls a "screen" or "out-the-back" play',
    'Leave early, run flat and hard across the 10\'s face',
    'max',
    'Fix the inside defender and the 10 channel so the ball out the back is against a broken line.',
    'If a back is running the screen, take the trailing support arc instead.',
    'A defence that ignores the decoy and drifts; counter by giving the decoy the ball.',
    [[-9, 6], [-6, 8], [-3, 10], [-0.5, 11.5]]],
  ['Kick-off catch and drive', 'Maul', 'kick landing',
    'You are the designated restart catcher',
    'Jump at the peak of the lift, land facing your own posts',
    'cruise',
    'Secure the restart and give a stable platform for the exit kick.',
    'If 4 is the catcher, become the front lifter and then the first sealer.',
    'A contest jumper timing you; counter by varying the pod that jumps.',
    [[0, 0], [-1.5, 0.5], [-3, 1.2], [-4.5, 2]]],
  ['Cleanout square arc', 'Cleanout', 'tackle contact',
    'A team-mate is tackled in the far channel',
    'Leave on contact, run the outside-in arc',
    'sprint',
    'Arrive square through the gate, hit the jackal\'s hip and clear him beyond the ball.',
    'If the ball is safe, stand up as the pillar and let 9 play.',
    'A jackal who latches early; counter by hitting through the shoulder, not the back.',
    [[-3, 4], [-1.6, 2], [-0.4, 0.6], [0.6, -0.3]]],
  ['Reload to middle third', 'Fold', 'ruck',
    'The ball has been recycled on the far edge',
    'Fold on the recycle, behind the ruck',
    'jog',
    'Rebalance the field so the middle third is never empty for a swing-back play.',
    'If the middle is stocked, hold as the far-edge extra.',
    'A quick swing back; counter by pre-folding one forward each phase.',
    [[1, 14], [-2, 12], [-4, 8], [-5, 4]]],
]);
const d5 = mkLines(5, 'defence', [
  ['Openside guard press', 'Blitz', 'ruck',
    'Their pod receives the ball on your side',
    'Move on the pass, connected with your inside man',
    'cruise',
    'Win the collision behind the gain line and force them to play slow ball.',
    'If the guard slot is filled, take the next channel out.',
    'A pull-back behind your press; counter by keeping the outside man passive.',
    [[-2, 5], [-0.8, 5.4], [0.5, 5.8]]],
  ['Lineout tail contest to line', 'Fold', 'lineout tail',
    'You contest the tail and the throw goes elsewhere',
    'Land and go immediately; do not watch the ball',
    'sprint',
    'Convert from jumper to line defender before their first receiver gets the ball.',
    'If a back-rower has already filled the channel, take the one inside.',
    'A quick tail move; counter by not jumping and defending flat instead.',
    [[0, 0], [-1.5, -3], [-2, -7], [-2, -11]]],
  ['Inside-shoulder trail', 'Scramble', 'ruck',
    'A break is made outside you',
    'Turn immediately and run the infield arc',
    'sprint',
    'Take away the inside offload and the cut-back rather than chasing the outside.',
    'If a faster player is on the arc, drop behind as second cover.',
    'An attack that goes wide-wide; counter by trusting the edge and covering the middle.',
    [[-1, 6], [-3, 11], [-4, 16], [-4, 21]]],
]);

const LINES_F1: RunLine[] = [...a1, ...d1, ...a2, ...d2, ...a3, ...d3, ...a4, ...d4, ...a5, ...d5];
export default LINES_F1;
