/**
 * BAKEFALLS — run the recorded-physics pipeline.
 *
 * Solves the deterministic fall model across the whole tackle grid and packs
 * the recordings into a quantized, mirror-halved bank:
 *
 *     src/physics/fallBank.data.ts   (generated — do not edit by hand)
 *
 * Only the 11 "lead-limb" core channels are stored per recording (the left
 * limbs are derived at run time by a documented constant mirror, and a fall
 * to the left reuses the same curves), which halves the file.
 *
 * The tool also verifies every recording numerically (finite, in-range,
 * monotone toward the ground, joint limits respected, bitwise determinism)
 * before it is allowed to write the bank.
 *
 * Usage:  npx vite-node tools/bakeFalls.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  solveFall, gridDescs, FALL_N, CH, FALL_T, CH_CORE, CORE_ROWS,
} from '../src/physics/falls';
import type { FallDesc } from '../src/physics/falls';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '../src/physics/fallBank.data.ts');
const SCALE = 10_000;               // int16 quantization: ±3.27 rad @ 1e-4

interface Entry {
  meta: { kind: 'FALL' | 'ROLL'; speed: number; hitH: number; massR: number; dir: number };
  full: Float32Array;               // CH_COUNT × FALL_N (verification only)
}

const dirNum = (d: FallDesc['dir']) => (d === 'F' ? 0 : d === 'B' ? 1 : 0.5);

function build(): void {
  const entries: Entry[] = [];
  const problems: string[] = [];
  const check = (label: string, ok: boolean) => { if (!ok) problems.push(label); };

  for (const kind of ['FALL', 'ROLL'] as const) {
    for (const d of gridDescs(kind)) {
      const label = `${kind} v${d.speed} h${d.hitH} m${d.massR} d${d.dir}`;
      const full = solveFall(d);
      for (let i = 0; i < full.length; i++) check(`${label} finite@${i}`, Number.isFinite(full[i]));
      const end = (c: number) => full[c * FALL_N + FALL_N - 1];
      const at = (c: number, f: number) => full[c * FALL_N + Math.min(FALL_N - 1, Math.floor(f * FALL_N))];
      const ePitch = end(CH.pitch);
      const eTwist = end(CH.twistZ);
      // lateral falls must have laid the body over sideways; sagittal falls
      // must end prone-ish (a roll settles braced, not flat)
      if (d.dir === 'S') {
        // a laid-over FALL ends flat on his side (|twist|≈π/2); a ROLL is a
        // braced peel-off that stops part-way over — both must still carry
        // the lateral hit rather than toppling forward
        check(`${label} lateral twist carried`,
          Math.abs(eTwist) > (kind === 'ROLL' ? 0.9 : 1.0));
      } else {
        check(`${label} ends prone-ish`, Math.abs(Math.abs(ePitch) - Math.PI / 2) < (kind === 'ROLL' ? 0.85 : 0.6));
        check(`${label} F/B twist modest`, Math.abs(eTwist) < 0.8);
        // from a third of the way in he must be heading to the ground
        const targetSign = d.dir === 'B' ? -1 : 1;
        for (const f of [0.3, 0.6, 0.9]) {
          const p = at(CH.pitch, f);
          check(`${label} heading down@${f}`, Math.sign(p) === targetSign || Math.abs(p) < 0.3);
        }
      }
      // joints inside legal angular range the whole way
      for (const c of [CH.armRflex, CH.armRab, CH.armRelbow, CH.legRflex, CH.legRab, CH.legRknee]) {
        for (let s = 0; s < FALL_N; s++) {
          const v = full[c * FALL_N + s];
          check(`${label} ch${c}@${s}`, v >= -0.3 && v <= 2.3);
        }
      }
      entries.push({ meta: { kind: d.kind, speed: d.speed, hitH: d.hitH, massR: d.massR, dir: dirNum(d.dir) }, full });
    }
  }

  // determinism: same input twice must be bitwise identical
  const a = solveFall({ kind: 'FALL', speed: 7.5, hitH: 0.6, massR: 1, dir: 'S' });
  const b = solveFall({ kind: 'FALL', speed: 7.5, hitH: 0.6, massR: 1, dir: 'S' });
  let same = a.length === b.length;
  if (same) for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) { same = false; break; }
  check('determinism (FALL v7.5 h0.6 m1 S)', same);

  /* ---- pack: 11 core rows, int16 @ SCALE, little-endian ---- */
  const total = entries.length * CH_CORE * FALL_N;
  const bytes = Buffer.alloc(total * 2);
  let o = 0;
  for (const e of entries) {
    for (const c of CORE_ROWS) {
      for (let s = 0; s < FALL_N; s++) {
        const v = Math.max(-3.2767, Math.min(3.2767, e.full[c * FALL_N + s]));
        bytes.writeInt16LE(Math.round(v * SCALE), o);
        o += 2;
      }
    }
  }
  const dataB64 = bytes.toString('base64');
  const meta = entries.map((e) => e.meta);

  const src = `/**
 * FALLBANK (GENERATED by tools/bakeFalls.ts — DO NOT EDIT BY HAND)
 *
 * Recorded tackle physics: ${entries.length} deterministic falls across the
 * bake grid × ${CH_CORE} core channels × ${FALL_N} samples @ 30 Hz, quantized
 * int16 at 1e-4 rad and packed base64. Only the right-limb lead curves are
 * stored — the left limbs and the left-side mirror are derived at run time
 * (see fallBank.ts) so the file is roughly half its naive size.
 *
 * Regenerate with:  npx vite-node tools/bakeFalls.ts
 */
export const FALL_BANK_VERSION = 1;
export const FALL_BANK_N = ${FALL_N};
export const FALL_BANK_CH = ${CH_CORE};
export const FALL_BANK_HZ = 30;
export const FALL_BANK_SCALE = ${SCALE};
export const FALL_BANK_SECONDS = ${FALL_T};

export type FallBankDir = 0 | 0.5 | 1;   // F | S | B
export interface FallBankMeta {
  kind: 'FALL' | 'ROLL';
  speed: number;   // m/s
  hitH: number;    // 0..1
  massR: number;   // tackler/carrier momentum ratio
  dir: FallBankDir;
}
export const FALL_BANK_META: FallBankMeta[] = ${JSON.stringify(meta)};

export const FALL_BANK_B64 = '${dataB64}';
`;

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, src);
  const kb = (bytes.length / 1024).toFixed(1);
  console.log(`[bake] wrote ${OUT}`);
  console.log(`[bake] entries=${entries.length} core=${CH_CORE} samples=${FALL_N} packed=${kb}KB base64=${(dataB64.length / 1024).toFixed(1)}KB sourceLines=${src.split('\n').length}`);
  const kinds: Record<string, number> = {};
  for (const m of meta) kinds[m.kind] = (kinds[m.kind] ?? 0) + 1;
  const dirs: Record<string, number> = {};
  for (const m of meta) dirs[m.dir === 0 ? 'F' : m.dir === 1 ? 'B' : 'S'] = (dirs[m.dir === 0 ? 'F' : m.dir === 1 ? 'B' : 'S'] ?? 0) + 1;
  console.log('[bake] kinds:', Object.entries(kinds).map(([k, v]) => `${k}=${v}`).join(' '), ' dirs:', Object.entries(dirs).map(([k, v]) => `${k}:${v}`).join(' '));
  if (problems.length) {
    console.log(`[bake] ${problems.length} VERIFY FAILURES (first 15):`);
    for (const p of problems.slice(0, 15)) console.log('   -', p);
    process.exitCode = 1;
  } else {
    console.log('[bake] verification: ALL PASS');
  }
}

build();
